package com.qherp.api.system.init;

import com.qherp.api.system.permission.SystemPermission;
import com.qherp.api.system.permission.SystemPermissionRepository;
import com.qherp.api.system.permission.SystemPermissionType;
import com.qherp.api.system.permission.SystemRolePermission;
import com.qherp.api.system.permission.SystemRolePermissionRepository;
import com.qherp.api.system.role.SystemRole;
import com.qherp.api.system.role.SystemRoleRepository;
import com.qherp.api.system.role.SystemRoleStatus;
import com.qherp.api.system.user.SystemUser;
import com.qherp.api.system.user.SystemUserRepository;
import com.qherp.api.system.user.SystemUserRole;
import com.qherp.api.system.user.SystemUserRoleRepository;
import com.qherp.api.system.user.SystemUserStatus;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Map;
import java.util.LinkedHashMap;

@Component
public class AccountPermissionInitializer implements ApplicationRunner {

	private static final String SYSTEM_OPERATOR = "system";

	private static final String ADMIN_USERNAME = "admin";

	private static final String SYSTEM_ADMIN_ROLE_CODE = "SYSTEM_ADMIN";

	private static final List<PermissionSeed> PERMISSION_SEEDS = List.of(
			new PermissionSeed("system", "系统管理", SystemPermissionType.MENU, null, "/system", null, null, 0),
			new PermissionSeed("system:user", "用户管理", SystemPermissionType.MENU, "system", "/system/users", null,
					null, 10),
			new PermissionSeed("system:user:view", "查看用户", SystemPermissionType.ACTION, "system:user",
					"/system/users", "GET", "/api/admin/users/**", 11),
			new PermissionSeed("system:user:create", "创建用户", SystemPermissionType.ACTION, "system:user",
					"/system/users", "POST", "/api/admin/users", 12),
			new PermissionSeed("system:user:update", "更新、启用、停用用户", SystemPermissionType.ACTION, "system:user",
					"/system/users", "PUT", "/api/admin/users/**", 13),
			new PermissionSeed("system:user:reset-password", "重置用户密码", SystemPermissionType.ACTION, "system:user",
					"/system/users", "PUT", "/api/admin/users/{id}/password", 14),
			new PermissionSeed("system:role", "角色管理", SystemPermissionType.MENU, "system", "/system/roles", null,
					null, 20),
			new PermissionSeed("system:role:view", "查看角色", SystemPermissionType.ACTION, "system:role",
					"/system/roles", "GET", "/api/admin/roles/**", 21),
			new PermissionSeed("system:role:create", "创建角色", SystemPermissionType.ACTION, "system:role",
					"/system/roles", "POST", "/api/admin/roles", 22),
			new PermissionSeed("system:role:update", "更新、启用、停用角色", SystemPermissionType.ACTION, "system:role",
					"/system/roles", "PUT", "/api/admin/roles/**", 23),
			new PermissionSeed("system:role:assign-permission", "分配角色权限", SystemPermissionType.ACTION,
					"system:role", "/system/roles", "PUT", "/api/admin/roles/{id}/permissions", 24),
			new PermissionSeed("system:permission", "权限管理", SystemPermissionType.MENU, "system",
					"/system/permissions", null, null, 30),
			new PermissionSeed("system:permission:view", "查看权限树", SystemPermissionType.ACTION, "system:permission",
					"/system/permissions", "GET", "/api/admin/permissions/tree", 31),
			new PermissionSeed("system:audit", "审计日志", SystemPermissionType.MENU, "system", "/system/audit-logs",
					null, null, 40),
			new PermissionSeed("system:audit:view", "查看账号权限审计", SystemPermissionType.ACTION, "system:audit",
					"/system/audit-logs", "GET", "/api/admin/audit-logs", 41),
			new PermissionSeed("system:business-period", "业务期间", SystemPermissionType.MENU, "system",
					"/system/business-periods", null, null, 50),
			new PermissionSeed("system:business-period:view", "查看业务期间", SystemPermissionType.ACTION,
					"system:business-period", "/system/business-periods", "GET",
					"/api/admin/system/business-periods/**", 51),
			new PermissionSeed("system:business-period:create", "创建业务期间", SystemPermissionType.ACTION,
					"system:business-period", "/system/business-periods", "POST",
					"/api/admin/system/business-periods", 52),
			new PermissionSeed("system:business-period:update", "更新业务期间", SystemPermissionType.ACTION,
					"system:business-period", "/system/business-periods", "PUT",
					"/api/admin/system/business-periods/{id}", 53),
			new PermissionSeed("system:business-period:lock", "锁定业务期间", SystemPermissionType.ACTION,
					"system:business-period", "/system/business-periods", "POST",
					"/api/admin/system/business-periods/{id}/lock", 54),
			new PermissionSeed("system:business-period:unlock", "解锁业务期间", SystemPermissionType.ACTION,
					"system:business-period", "/system/business-periods", "POST",
					"/api/admin/system/business-periods/{id}/unlock", 55),
			new PermissionSeed("master", "基础资料", SystemPermissionType.MENU, null, "/master", null, null, 100),
			new PermissionSeed("master:unit", "计量单位", SystemPermissionType.MENU, "master", "/master/units",
					null, null, 110),
			new PermissionSeed("master:unit:view", "查看计量单位", SystemPermissionType.ACTION, "master:unit",
					"/master/units", "GET", "/api/admin/master/units/**", 111),
			new PermissionSeed("master:unit:create", "创建计量单位", SystemPermissionType.ACTION, "master:unit",
					"/master/units", "POST", "/api/admin/master/units", 112),
			new PermissionSeed("master:unit:update", "更新、启用、停用计量单位", SystemPermissionType.ACTION,
					"master:unit", "/master/units", "PUT", "/api/admin/master/units/**", 113),
			new PermissionSeed("master:unit-conversion", "单位换算", SystemPermissionType.MENU, "master",
					"/master/unit-conversions", null, null, 114),
			new PermissionSeed("master:unit-conversion:view", "查看单位换算", SystemPermissionType.ACTION,
					"master:unit-conversion", "/master/unit-conversions", "GET",
					"/api/admin/master/unit-conversions/**", 115),
			new PermissionSeed("master:unit-conversion:create", "创建单位换算", SystemPermissionType.ACTION,
					"master:unit-conversion", "/master/unit-conversions", "POST",
					"/api/admin/master/unit-conversions", 116),
			new PermissionSeed("master:unit-conversion:update", "更新单位换算", SystemPermissionType.ACTION,
					"master:unit-conversion", "/master/unit-conversions", "PUT",
					"/api/admin/master/unit-conversions/{id}", 117),
			new PermissionSeed("master:unit-conversion:enable", "启用单位换算", SystemPermissionType.ACTION,
					"master:unit-conversion", "/master/unit-conversions", "PUT",
					"/api/admin/master/unit-conversions/{id}/enable", 118),
			new PermissionSeed("master:unit-conversion:disable", "停用单位换算", SystemPermissionType.ACTION,
					"master:unit-conversion", "/master/unit-conversions", "PUT",
					"/api/admin/master/unit-conversions/{id}/disable", 119),
			new PermissionSeed("master:warehouse", "仓库", SystemPermissionType.MENU, "master",
					"/master/warehouses", null, null, 120),
			new PermissionSeed("master:warehouse:view", "查看仓库", SystemPermissionType.ACTION, "master:warehouse",
					"/master/warehouses", "GET", "/api/admin/master/warehouses/**", 121),
			new PermissionSeed("master:warehouse:create", "创建仓库", SystemPermissionType.ACTION,
					"master:warehouse", "/master/warehouses", "POST", "/api/admin/master/warehouses", 122),
			new PermissionSeed("master:warehouse:update", "更新、启用、停用仓库", SystemPermissionType.ACTION,
					"master:warehouse", "/master/warehouses", "PUT", "/api/admin/master/warehouses/**", 123),
			new PermissionSeed("master:supplier", "供应商", SystemPermissionType.MENU, "master",
					"/master/suppliers", null, null, 130),
			new PermissionSeed("master:supplier:view", "查看供应商", SystemPermissionType.ACTION, "master:supplier",
					"/master/suppliers", "GET", "/api/admin/master/suppliers/**", 131),
			new PermissionSeed("master:supplier:create", "创建供应商", SystemPermissionType.ACTION,
					"master:supplier", "/master/suppliers", "POST", "/api/admin/master/suppliers", 132),
			new PermissionSeed("master:supplier:update", "更新、启用、停用供应商", SystemPermissionType.ACTION,
					"master:supplier", "/master/suppliers", "PUT", "/api/admin/master/suppliers/**", 133),
			new PermissionSeed("master:customer", "客户", SystemPermissionType.MENU, "master", "/master/customers",
					null, null, 140),
			new PermissionSeed("master:customer:view", "查看客户", SystemPermissionType.ACTION, "master:customer",
					"/master/customers", "GET", "/api/admin/master/customers/**", 141),
			new PermissionSeed("master:customer:create", "创建客户", SystemPermissionType.ACTION,
					"master:customer", "/master/customers", "POST", "/api/admin/master/customers", 142),
			new PermissionSeed("master:customer:update", "更新、启用、停用客户", SystemPermissionType.ACTION,
					"master:customer", "/master/customers", "PUT", "/api/admin/master/customers/**", 143),
			new PermissionSeed("master:customer-settlement:view", "查看客户结算税务", SystemPermissionType.ACTION,
					"master:customer", "/master/customers", "GET",
					"/api/admin/master/customers/{id}/settlement-tax", 144),
			new PermissionSeed("master:customer-settlement:update", "更新客户结算税务", SystemPermissionType.ACTION,
					"master:customer", "/master/customers", "PUT",
					"/api/admin/master/customers/{id}/settlement-tax", 145),
			new PermissionSeed("master:customer-settlement:sensitive-view", "查看客户敏感结算资料",
					SystemPermissionType.ACTION, "master:customer", "/master/customers", null, null, 146),
			new PermissionSeed("master:customer-settlement:sensitive-update", "维护客户敏感结算资料",
					SystemPermissionType.ACTION, "master:customer", "/master/customers", null, null, 147),
			new PermissionSeed("master:supplier-settlement:view", "查看供应商结算税务", SystemPermissionType.ACTION,
					"master:supplier", "/master/suppliers", "GET",
					"/api/admin/master/suppliers/{id}/settlement-tax", 148),
			new PermissionSeed("master:supplier-settlement:update", "更新供应商结算税务", SystemPermissionType.ACTION,
					"master:supplier", "/master/suppliers", "PUT",
					"/api/admin/master/suppliers/{id}/settlement-tax", 149),
			new PermissionSeed("master:supplier-settlement:sensitive-view", "查看供应商敏感结算资料",
					SystemPermissionType.ACTION, "master:supplier", "/master/suppliers", null, null, 150),
			new PermissionSeed("master:supplier-settlement:sensitive-update", "维护供应商敏感结算资料",
					SystemPermissionType.ACTION, "master:supplier", "/master/suppliers", null, null, 151),
			new PermissionSeed("master:coding-rule", "编码规则", SystemPermissionType.MENU, "master",
					"/master/coding-rules", null, null, 160),
			new PermissionSeed("master:coding-rule:view", "查看编码规则", SystemPermissionType.ACTION,
					"master:coding-rule", "/master/coding-rules", "GET", "/api/admin/coding-rules/**", 161),
			new PermissionSeed("master:coding-rule:create", "创建编码规则", SystemPermissionType.ACTION,
					"master:coding-rule", "/master/coding-rules", "POST", "/api/admin/coding-rules", 162),
			new PermissionSeed("master:coding-rule:update", "更新编码规则", SystemPermissionType.ACTION,
					"master:coding-rule", "/master/coding-rules", "PUT", "/api/admin/coding-rules/{id}", 163),
			new PermissionSeed("master:coding-rule:enable", "启用编码规则", SystemPermissionType.ACTION,
					"master:coding-rule", "/master/coding-rules", "PUT",
					"/api/admin/coding-rules/{id}/enable", 164),
			new PermissionSeed("master:coding-rule:disable", "停用编码规则", SystemPermissionType.ACTION,
					"master:coding-rule", "/master/coding-rules", "PUT",
					"/api/admin/coding-rules/{id}/disable", 165),
			new PermissionSeed("master:coding-rule:generate", "生成业务编码", SystemPermissionType.ACTION,
					"master:coding-rule", "/master/coding-rules", "POST", "/api/admin/coding-rules/generate",
					166),
			new PermissionSeed("material", "物料管理", SystemPermissionType.MENU, null, "/materials", null, null,
					200),
			new PermissionSeed("master:material-category", "物料分类", SystemPermissionType.MENU, "material",
					"/materials/categories", null, null, 210),
			new PermissionSeed("master:material-category:view", "查看物料分类", SystemPermissionType.ACTION,
					"master:material-category", "/materials/categories", "GET",
					"/api/admin/master/material-categories/**", 211),
			new PermissionSeed("master:material-category:create", "创建物料分类", SystemPermissionType.ACTION,
					"master:material-category", "/materials/categories", "POST",
					"/api/admin/master/material-categories", 212),
			new PermissionSeed("master:material-category:update", "更新、启用、停用物料分类", SystemPermissionType.ACTION,
					"master:material-category", "/materials/categories", "PUT",
					"/api/admin/master/material-categories/**", 213),
			new PermissionSeed("master:material", "物料档案", SystemPermissionType.MENU, "material",
					"/materials/items", null, null, 220),
			new PermissionSeed("master:material:view", "查看物料", SystemPermissionType.ACTION, "master:material",
					"/materials/items", "GET", "/api/admin/master/materials/**", 221),
			new PermissionSeed("master:material:create", "创建物料", SystemPermissionType.ACTION, "master:material",
					"/materials/items", "POST", "/api/admin/master/materials", 222),
			new PermissionSeed("master:material:update", "更新、启用、停用物料", SystemPermissionType.ACTION,
					"master:material", "/materials/items", "PUT", "/api/admin/master/materials/**", 223),
			new PermissionSeed("master:material-cost:view", "查看物料成本属性", SystemPermissionType.ACTION,
					"master:material", "/materials/items", "GET", "/api/admin/master/materials/**", 224),
			new PermissionSeed("master:material-cost:update", "维护物料成本属性", SystemPermissionType.ACTION,
					"master:material", "/materials/items", "PUT", "/api/admin/master/materials/{id}", 225),
			new PermissionSeed("master:material:import", "导入新增物料", SystemPermissionType.ACTION,
					"master:material", "/materials/items", "POST", "/api/admin/imports/materials/**", 226),
			new PermissionSeed("master:material:export", "导出物料", SystemPermissionType.ACTION,
					"master:material", "/materials/items", "POST", "/api/admin/exports/materials", 227),
			new PermissionSeed("material:bom", "BOM 管理", SystemPermissionType.MENU, "material",
					"/materials/boms", null, null, 230),
			new PermissionSeed("material:bom:view", "查看 BOM", SystemPermissionType.ACTION, "material:bom",
					"/materials/boms", "GET", "/api/admin/boms/**", 231),
			new PermissionSeed("material:bom:create", "创建 BOM", SystemPermissionType.ACTION, "material:bom",
					"/materials/boms", "POST", "/api/admin/boms", 232),
			new PermissionSeed("material:bom:update", "更新 BOM", SystemPermissionType.ACTION, "material:bom",
					"/materials/boms", "PUT", "/api/admin/boms/{id}", 233),
			new PermissionSeed("material:bom:copy", "复制 BOM 版本", SystemPermissionType.ACTION, "material:bom",
					"/materials/boms", "POST", "/api/admin/boms/{id}/copy", 234),
			new PermissionSeed("material:bom:enable", "启用 BOM", SystemPermissionType.ACTION, "material:bom",
					"/materials/boms", "PUT", "/api/admin/boms/{id}/enable", 235),
			new PermissionSeed("material:bom:disable", "停用 BOM", SystemPermissionType.ACTION, "material:bom",
					"/materials/boms", "PUT", "/api/admin/boms/{id}/disable", 236),
			new PermissionSeed("material:bom:import", "导入 BOM 草稿", SystemPermissionType.ACTION, "material:bom",
					"/materials/boms", "POST", "/api/admin/imports/bom-drafts/**", 247),
			new PermissionSeed("material:bom:export", "导出 BOM 草稿", SystemPermissionType.ACTION, "material:bom",
					"/materials/boms", "POST", "/api/admin/exports/bom-drafts/**", 248),
			new PermissionSeed("material:bom-eco:view", "查看 BOM 工程变更", SystemPermissionType.ACTION,
					"material:bom", "/materials/boms", "GET", "/api/admin/bom-engineering-changes/**", 237),
			new PermissionSeed("material:bom-eco:create", "创建 BOM 工程变更", SystemPermissionType.ACTION,
					"material:bom", "/materials/boms", "POST", "/api/admin/bom-engineering-changes", 238),
			new PermissionSeed("material:bom-eco:update", "更新 BOM 工程变更", SystemPermissionType.ACTION,
					"material:bom", "/materials/boms", "PUT", "/api/admin/bom-engineering-changes/{id}", 239),
			new PermissionSeed("material:bom-eco:apply", "应用 BOM 工程变更", SystemPermissionType.ACTION,
					"material:bom", "/materials/boms", "PUT", "/api/admin/bom-engineering-changes/{id}/apply",
					240),
			new PermissionSeed("material:bom-eco:apply-approve", "审批应用 BOM 工程变更",
					SystemPermissionType.ACTION, "material:bom", "/materials/boms", "POST",
					"/api/admin/approval-tasks/{id}/approve", 249),
			new PermissionSeed("material:bom-eco:cancel", "取消 BOM 工程变更", SystemPermissionType.ACTION,
					"material:bom", "/materials/boms", "PUT", "/api/admin/bom-engineering-changes/{id}/cancel",
					241),
			new PermissionSeed("material:substitute:view", "查看替代料", SystemPermissionType.ACTION,
					"material:bom", "/materials/boms", "GET", "/api/admin/material-substitutes/**", 242),
			new PermissionSeed("material:substitute:create", "创建替代料", SystemPermissionType.ACTION,
					"material:bom", "/materials/boms", "POST", "/api/admin/material-substitutes", 243),
			new PermissionSeed("material:substitute:update", "更新替代料", SystemPermissionType.ACTION,
					"material:bom", "/materials/boms", "PUT", "/api/admin/material-substitutes/{id}", 244),
			new PermissionSeed("material:substitute:enable", "启用替代料", SystemPermissionType.ACTION,
					"material:bom", "/materials/boms", "PUT", "/api/admin/material-substitutes/{id}/enable",
					245),
			new PermissionSeed("material:substitute:disable", "停用替代料", SystemPermissionType.ACTION,
					"material:bom", "/materials/boms", "PUT", "/api/admin/material-substitutes/{id}/disable",
					246),
			new PermissionSeed("inventory", "库存管理", SystemPermissionType.MENU, null, "/inventory/balances",
					null, null, 300),
			new PermissionSeed("inventory:balance:view", "查看库存余额", SystemPermissionType.ACTION, "inventory",
					"/inventory/balances", "GET", "/api/admin/inventory/balances", 301),
			new PermissionSeed("inventory:valuation:view", "查看库存成本金额", SystemPermissionType.ACTION, "inventory",
					"/inventory/balances", "GET", "/api/admin/inventory/balances", 302),
			new PermissionSeed("inventory:reservation:view", "查看库存预留占用", SystemPermissionType.ACTION,
					"inventory", "/inventory/reservations", "GET", "/api/admin/inventory/reservations/**", 303),
			new PermissionSeed("inventory:movement:view", "查看库存变动", SystemPermissionType.ACTION, "inventory",
					"/inventory/movements", "GET", "/api/admin/inventory/movements", 304),
			new PermissionSeed("inventory:batch:view", "查看批次档案", SystemPermissionType.ACTION, "inventory",
					"/inventory/batches", "GET", "/api/admin/inventory/batches/**", 309),
			new PermissionSeed("inventory:serial:view", "查看序列号档案", SystemPermissionType.ACTION, "inventory",
					"/inventory/serials", "GET", "/api/admin/inventory/serials/**", 310),
			new PermissionSeed("inventory:trace:view", "查看来源去向追溯", SystemPermissionType.ACTION,
					"inventory", "/inventory/traces", "GET", "/api/admin/inventory/traces/**", 311),
			new PermissionSeed("inventory:document:view", "查看库存单据", SystemPermissionType.ACTION, "inventory",
					"/inventory/documents", "GET", "/api/admin/inventory/documents/**", 305),
			new PermissionSeed("inventory:document:create", "创建库存单据", SystemPermissionType.ACTION, "inventory",
					"/inventory/documents", "POST", "/api/admin/inventory/documents", 306),
			new PermissionSeed("inventory:document:update", "更新库存单据", SystemPermissionType.ACTION, "inventory",
					"/inventory/documents", "PUT", "/api/admin/inventory/documents/{id}", 307),
			new PermissionSeed("inventory:document:post", "过账库存单据", SystemPermissionType.ACTION, "inventory",
					"/inventory/documents", "PUT", "/api/admin/inventory/documents/{id}/post", 308),
			new PermissionSeed("inventory:cost-layer:view", "查看库存成本层", SystemPermissionType.ACTION,
					"inventory", "/inventory/cost-layers", "GET", "/api/admin/inventory/cost-layers/**", 312),
			new PermissionSeed("inventory:reconciliation:view", "查看库存价值对账", SystemPermissionType.ACTION,
					"inventory", "/inventory/reconciliations", "GET", "/api/admin/inventory/reconciliations", 313),
			new PermissionSeed("inventory:warehouse-transfer:view", "查看仓库调拨", SystemPermissionType.ACTION,
					"inventory", "/inventory/warehouse-transfers", "GET",
					"/api/admin/inventory/warehouse-transfers/**", 314),
			new PermissionSeed("inventory:warehouse-transfer:create", "创建仓库调拨", SystemPermissionType.ACTION,
					"inventory", "/inventory/warehouse-transfers", "POST", "/api/admin/inventory/warehouse-transfers",
					315),
			new PermissionSeed("inventory:warehouse-transfer:update", "更新仓库调拨", SystemPermissionType.ACTION,
					"inventory", "/inventory/warehouse-transfers", "PUT",
					"/api/admin/inventory/warehouse-transfers/{id}", 316),
			new PermissionSeed("inventory:warehouse-transfer:post", "过账仓库调拨", SystemPermissionType.ACTION,
					"inventory", "/inventory/warehouse-transfers", "PUT",
					"/api/admin/inventory/warehouse-transfers/{id}/post", 317),
			new PermissionSeed("inventory:warehouse-transfer:cancel", "取消仓库调拨", SystemPermissionType.ACTION,
					"inventory", "/inventory/warehouse-transfers", "PUT",
					"/api/admin/inventory/warehouse-transfers/{id}/cancel", 318),
			new PermissionSeed("inventory:ownership-conversion:view", "查看库存所有权转换",
					SystemPermissionType.ACTION, "inventory", "/inventory/ownership-conversions", "GET",
					"/api/admin/inventory/ownership-conversions/**", 319),
			new PermissionSeed("inventory:ownership-conversion:create", "创建库存所有权转换",
					SystemPermissionType.ACTION, "inventory", "/inventory/ownership-conversions", "POST",
					"/api/admin/inventory/ownership-conversions", 320),
			new PermissionSeed("inventory:ownership-conversion:update", "更新库存所有权转换",
					SystemPermissionType.ACTION, "inventory", "/inventory/ownership-conversions", "PUT",
					"/api/admin/inventory/ownership-conversions/{id}", 321),
			new PermissionSeed("inventory:ownership-conversion:submit", "提交库存所有权转换审批",
					SystemPermissionType.ACTION, "inventory", "/inventory/ownership-conversions", "PUT",
					"/api/admin/inventory/ownership-conversions/{id}/submit-approval", 322),
			new PermissionSeed("inventory:ownership-conversion:withdraw", "撤回库存所有权转换审批",
					SystemPermissionType.ACTION, "inventory", "/inventory/ownership-conversions", "PUT",
					"/api/admin/inventory/ownership-conversions/{id}/withdraw", 323),
			new PermissionSeed("inventory:ownership-conversion:cancel", "取消库存所有权转换",
					SystemPermissionType.ACTION, "inventory", "/inventory/ownership-conversions", "PUT",
					"/api/admin/inventory/ownership-conversions/{id}/cancel", 323),
			new PermissionSeed("inventory:ownership-conversion:post-approve", "审批库存所有权转换过账",
					SystemPermissionType.ACTION, "inventory", "/platform/approvals", "POST",
					"/api/admin/approval-tasks/{id}/approve", 324),
			new PermissionSeed("inventory:stocktake:view", "查看库存盘点", SystemPermissionType.ACTION,
					"inventory", "/inventory/stocktakes", "GET", "/api/admin/inventory/stocktakes/**", 325),
			new PermissionSeed("inventory:stocktake:create", "创建库存盘点", SystemPermissionType.ACTION,
					"inventory", "/inventory/stocktakes", "POST", "/api/admin/inventory/stocktakes", 326),
			new PermissionSeed("inventory:stocktake:update", "更新库存盘点", SystemPermissionType.ACTION,
					"inventory", "/inventory/stocktakes", "PUT", "/api/admin/inventory/stocktakes/**", 327),
			new PermissionSeed("inventory:stocktake:submit", "提交库存盘点审批", SystemPermissionType.ACTION,
					"inventory", "/inventory/stocktakes", "PUT", "/api/admin/inventory/stocktakes/{id}/submit-approval",
					328),
			new PermissionSeed("inventory:stocktake:cancel", "取消库存盘点", SystemPermissionType.ACTION,
					"inventory", "/inventory/stocktakes", "PUT", "/api/admin/inventory/stocktakes/{id}/cancel",
					329),
			new PermissionSeed("inventory:stocktake:variance-approve", "审批库存盘点盘差",
					SystemPermissionType.ACTION, "inventory", "/platform/approvals", "POST",
					"/api/admin/approval-tasks/{id}/approve", 330),
			new PermissionSeed("inventory:valuation-adjustment:view", "查看库存估值调整",
					SystemPermissionType.ACTION, "inventory", "/inventory/valuation-adjustments", "GET",
					"/api/admin/inventory/valuation-adjustments/**", 331),
			new PermissionSeed("inventory:valuation-adjustment:create", "创建库存估值调整",
					SystemPermissionType.ACTION, "inventory", "/inventory/valuation-adjustments", "POST",
					"/api/admin/inventory/valuation-adjustments", 332),
			new PermissionSeed("inventory:valuation-adjustment:update", "更新库存估值调整",
					SystemPermissionType.ACTION, "inventory", "/inventory/valuation-adjustments", "PUT",
					"/api/admin/inventory/valuation-adjustments/{id}", 333),
			new PermissionSeed("inventory:valuation-adjustment:submit", "提交库存估值调整审批",
					SystemPermissionType.ACTION, "inventory", "/inventory/valuation-adjustments", "PUT",
					"/api/admin/inventory/valuation-adjustments/{id}/submit-approval", 334),
			new PermissionSeed("inventory:valuation-adjustment:withdraw", "撤回库存估值调整审批",
					SystemPermissionType.ACTION, "inventory", "/inventory/valuation-adjustments", "PUT",
					"/api/admin/inventory/valuation-adjustments/{id}/withdraw", 335),
			new PermissionSeed("inventory:valuation-adjustment:cancel", "取消库存估值调整",
					SystemPermissionType.ACTION, "inventory", "/inventory/valuation-adjustments", "PUT",
					"/api/admin/inventory/valuation-adjustments/{id}/cancel", 335),
			new PermissionSeed("inventory:valuation-adjustment:post-approve", "审批库存估值调整过账",
					SystemPermissionType.ACTION, "inventory", "/platform/approvals", "POST",
					"/api/admin/approval-tasks/{id}/approve", 336),
			new PermissionSeed("procurement", "采购管理", SystemPermissionType.MENU, null, "/procurement/orders",
					null, null, 350),
			new PermissionSeed("procurement:requisition:view", "查看采购请购", SystemPermissionType.ACTION,
					"procurement", "/procurement/requisitions", "GET", "/api/admin/procurement/requisitions/**",
					350),
			new PermissionSeed("procurement:requisition:create", "创建采购请购", SystemPermissionType.ACTION,
					"procurement", "/procurement/requisitions", "POST", "/api/admin/procurement/requisitions",
					350),
			new PermissionSeed("procurement:requisition:update", "更新采购请购", SystemPermissionType.ACTION,
					"procurement", "/procurement/requisitions", "PUT", "/api/admin/procurement/requisitions/{id}",
					350),
			new PermissionSeed("procurement:requisition:submit", "提交采购请购审批",
					SystemPermissionType.ACTION, "procurement", "/procurement/requisitions", "POST",
					"/api/admin/procurement/requisitions/{id}/submit-approval", 350),
			new PermissionSeed("procurement:requisition:approve", "审批采购请购", SystemPermissionType.ACTION,
					"procurement", "/platform/approvals", "POST", "/api/admin/approval-tasks/{id}/approve",
					350),
			new PermissionSeed("procurement:requisition:cancel", "取消采购请购", SystemPermissionType.ACTION,
					"procurement", "/procurement/requisitions", "PUT",
					"/api/admin/procurement/requisitions/{id}/cancel", 350),
			new PermissionSeed("procurement:requisition:close", "结案采购请购", SystemPermissionType.ACTION,
					"procurement", "/procurement/requisitions", "PUT",
					"/api/admin/procurement/requisitions/{id}/close", 350),
			new PermissionSeed("procurement:inquiry:view", "查看采购询价", SystemPermissionType.ACTION,
					"procurement", "/procurement/inquiries", "GET", "/api/admin/procurement/inquiries/**", 350),
			new PermissionSeed("procurement:inquiry:create", "创建采购询价", SystemPermissionType.ACTION,
					"procurement", "/procurement/inquiries", "POST", "/api/admin/procurement/inquiries", 350),
			new PermissionSeed("procurement:inquiry:update", "更新采购询价", SystemPermissionType.ACTION,
					"procurement", "/procurement/inquiries", "PUT", "/api/admin/procurement/inquiries/{id}", 350),
			new PermissionSeed("procurement:inquiry:release", "发布采购询价", SystemPermissionType.ACTION,
					"procurement", "/procurement/inquiries", "PUT",
					"/api/admin/procurement/inquiries/{id}/release", 350),
			new PermissionSeed("procurement:inquiry:complete", "完成采购询价", SystemPermissionType.ACTION,
					"procurement", "/procurement/inquiries", "PUT",
					"/api/admin/procurement/inquiries/{id}/complete", 350),
			new PermissionSeed("procurement:inquiry:cancel", "取消采购询价", SystemPermissionType.ACTION,
					"procurement", "/procurement/inquiries", "PUT",
					"/api/admin/procurement/inquiries/{id}/cancel", 350),
			new PermissionSeed("procurement:inquiry:award", "定标采购询价", SystemPermissionType.ACTION,
					"procurement", "/procurement/inquiries", "POST",
					"/api/admin/procurement/inquiries/{id}/award", 350),
			new PermissionSeed("procurement:quote:view", "查看供应商报价", SystemPermissionType.ACTION,
					"procurement", "/procurement/quotes", "GET",
					"/api/admin/procurement/inquiries/{id}/quotes/**", 350),
			new PermissionSeed("procurement:quote:create", "创建供应商报价", SystemPermissionType.ACTION,
					"procurement", "/procurement/quotes", "POST",
					"/api/admin/procurement/inquiries/{id}/quotes", 350),
			new PermissionSeed("procurement:quote:update", "更新供应商报价", SystemPermissionType.ACTION,
					"procurement", "/procurement/quotes", "PUT",
					"/api/admin/procurement/inquiries/{id}/quotes/{quoteId}", 350),
			new PermissionSeed("procurement:quote:import", "导入供应商报价", SystemPermissionType.ACTION,
					"procurement", "/procurement/quotes", "POST",
					"/api/admin/procurement/inquiries/{id}/quote-imports", 350),
			new PermissionSeed("procurement:quote:export", "导出供应商报价", SystemPermissionType.ACTION,
					"procurement", "/procurement/quotes", "POST",
					"/api/admin/export-tasks", 350),
			new PermissionSeed("procurement:quote:select", "选择供应商报价", SystemPermissionType.ACTION,
					"procurement", "/procurement/quotes", "PUT",
					"/api/admin/procurement/inquiries/{id}/quotes/{quoteId}/select", 350),
			new PermissionSeed("procurement:quote:cancel", "取消供应商报价", SystemPermissionType.ACTION,
					"procurement", "/procurement/quotes", "PUT",
					"/api/admin/procurement/inquiries/{id}/quotes/{quoteId}/cancel", 350),
			new PermissionSeed("procurement:price-agreement:view", "查看采购价格协议",
					SystemPermissionType.ACTION, "procurement", "/procurement/price-agreements", "GET",
					"/api/admin/procurement/price-agreements/**", 350),
			new PermissionSeed("procurement:price-agreement:create", "创建采购价格协议",
					SystemPermissionType.ACTION, "procurement", "/procurement/price-agreements", "POST",
					"/api/admin/procurement/price-agreements", 350),
			new PermissionSeed("procurement:price-agreement:update", "更新采购价格协议",
					SystemPermissionType.ACTION, "procurement", "/procurement/price-agreements", "PUT",
					"/api/admin/procurement/price-agreements/{id}", 350),
			new PermissionSeed("procurement:price-agreement:submit", "提交价格协议审批",
					SystemPermissionType.ACTION, "procurement", "/procurement/price-agreements", "POST",
					"/api/admin/procurement/price-agreements/{id}/submit-activation", 350),
			new PermissionSeed("procurement:price-agreement:disable", "停用采购价格协议",
					SystemPermissionType.ACTION, "procurement", "/procurement/price-agreements", "PUT",
					"/api/admin/procurement/price-agreements/{id}/disable", 350),
			new PermissionSeed("procurement:price-agreement:cancel", "取消采购价格协议",
					SystemPermissionType.ACTION, "procurement", "/procurement/price-agreements", "PUT",
					"/api/admin/procurement/price-agreements/{id}/cancel", 350),
			new PermissionSeed("procurement:price-agreement:approve", "审批价格协议激活",
					SystemPermissionType.ACTION, "procurement", "/platform/approvals", "POST",
					"/api/admin/approval-tasks/{id}/approve", 350),
			new PermissionSeed("procurement:order:view", "查看采购订单", SystemPermissionType.ACTION,
					"procurement", "/procurement/orders", "GET", "/api/admin/procurement/orders/**", 351),
			new PermissionSeed("procurement:order:create", "创建采购订单", SystemPermissionType.ACTION,
					"procurement", "/procurement/orders", "POST", "/api/admin/procurement/orders", 352),
			new PermissionSeed("procurement:order:update", "更新采购订单", SystemPermissionType.ACTION,
					"procurement", "/procurement/orders", "PUT", "/api/admin/procurement/orders/{id}", 353),
			new PermissionSeed("procurement:order:confirm", "确认采购订单", SystemPermissionType.ACTION,
					"procurement", "/procurement/orders", "PUT", "/api/admin/procurement/orders/{id}/confirm", 354),
			new PermissionSeed("procurement:order:cancel", "取消采购订单", SystemPermissionType.ACTION,
					"procurement", "/procurement/orders", "PUT", "/api/admin/procurement/orders/{id}/cancel", 355),
			new PermissionSeed("procurement:order:close", "关闭采购订单", SystemPermissionType.ACTION,
					"procurement", "/procurement/orders", "PUT", "/api/admin/procurement/orders/{id}/close", 356),
			new PermissionSeed("procurement:receipt:view", "查看采购入库", SystemPermissionType.ACTION,
					"procurement", "/procurement/receipts", "GET", "/api/admin/procurement/receipts/**", 357),
			new PermissionSeed("procurement:receipt:create", "创建采购入库", SystemPermissionType.ACTION,
					"procurement", "/procurement/receipts", "POST",
					"/api/admin/procurement/orders/{id}/receipts", 358),
			new PermissionSeed("procurement:receipt:update", "更新采购入库", SystemPermissionType.ACTION,
					"procurement", "/procurement/receipts", "PUT", "/api/admin/procurement/receipts/{id}", 359),
			new PermissionSeed("procurement:receipt:post", "过账采购入库", SystemPermissionType.ACTION,
					"procurement", "/procurement/receipts", "PUT", "/api/admin/procurement/receipts/{id}/post",
					360),
			new PermissionSeed("procurement:return:view", "查看采购退货", SystemPermissionType.ACTION,
					"procurement", "/procurement/returns", "GET", "/api/admin/procurement/returns/**", 361),
			new PermissionSeed("procurement:return:create", "创建采购退货", SystemPermissionType.ACTION,
					"procurement", "/procurement/returns", "POST", "/api/admin/procurement/returns", 362),
			new PermissionSeed("procurement:return:update", "更新采购退货草稿", SystemPermissionType.ACTION,
					"procurement", "/procurement/returns", "PUT", "/api/admin/procurement/returns/{id}", 363),
			new PermissionSeed("procurement:return:post", "过账采购退货", SystemPermissionType.ACTION,
					"procurement", "/procurement/returns", "PUT", "/api/admin/procurement/returns/{id}/post", 364),
			new PermissionSeed("procurement:return:cancel", "取消采购退货草稿", SystemPermissionType.ACTION,
					"procurement", "/procurement/returns", "PUT", "/api/admin/procurement/returns/{id}/cancel",
					365),
			new PermissionSeed("procurement:order:public-direct", "公共直采", SystemPermissionType.ACTION,
					"procurement", "/procurement/orders", "POST", "/api/admin/procurement/orders", 366),
			new PermissionSeed("procurement:order:exception-submit", "提交采购订单例外审批",
					SystemPermissionType.ACTION, "procurement", "/procurement/orders", "POST",
					"/api/admin/procurement/orders/{id}/submit-exception", 367),
			new PermissionSeed("procurement:order:exception-approve", "审批采购订单例外",
					SystemPermissionType.ACTION, "procurement", "/platform/approvals", "POST",
					"/api/admin/approval-tasks/{id}/approve", 368),
			new PermissionSeed("procurement:order:change", "变更采购订单", SystemPermissionType.ACTION,
					"procurement", "/procurement/orders", "POST", "/api/admin/procurement/orders/{id}/changes",
					368),
			new PermissionSeed("procurement:order:print", "打印采购订单", SystemPermissionType.ACTION,
					"procurement", "/procurement/orders", "POST", "/api/admin/print-tasks",
					368),
			new PermissionSeed("procurement:supply:view", "查看有效采购供给", SystemPermissionType.ACTION,
					"procurement", "/procurement/effective-supplies", "GET",
					"/api/admin/procurement/effective-supplies/**", 369),
			new PermissionSeed("procurement:supply:export", "导出有效采购供给", SystemPermissionType.ACTION,
					"procurement", "/procurement/effective-supplies", "POST",
					"/api/admin/export-tasks", 369),
			new PermissionSeed("procurement:document:export", "导出采购单据", SystemPermissionType.ACTION,
					"procurement", "/platform/document-tasks", "POST", "/api/admin/export-tasks", 369),
			new PermissionSeed("sales", "销售管理", SystemPermissionType.MENU, null, "/sales/orders", null, null,
					370),
			new PermissionSeed("sales:order:view", "查看销售订单", SystemPermissionType.ACTION, "sales",
					"/sales/orders", "GET", "/api/admin/sales/orders/**", 371),
			new PermissionSeed("sales:order:create", "创建销售订单", SystemPermissionType.ACTION, "sales",
					"/sales/orders", "POST", "/api/admin/sales/orders", 372),
			new PermissionSeed("sales:order:update", "更新销售订单草稿", SystemPermissionType.ACTION, "sales",
					"/sales/orders", "PUT", "/api/admin/sales/orders/{id}", 373),
			new PermissionSeed("sales:order:confirm", "确认销售订单", SystemPermissionType.ACTION, "sales",
					"/sales/orders", "PUT", "/api/admin/sales/orders/{id}/confirm", 374),
			new PermissionSeed("sales:order:cancel", "取消销售订单", SystemPermissionType.ACTION, "sales",
					"/sales/orders", "PUT", "/api/admin/sales/orders/{id}/cancel", 375),
			new PermissionSeed("sales:order:close", "关闭销售订单", SystemPermissionType.ACTION, "sales",
					"/sales/orders", "PUT", "/api/admin/sales/orders/{id}/close", 376),
			new PermissionSeed("sales:quote:view", "查看销售报价", SystemPermissionType.ACTION, "sales",
					"/sales/quotes", "GET", "/api/admin/sales/quotes/**", 401),
			new PermissionSeed("sales:quote:create", "创建销售报价", SystemPermissionType.ACTION, "sales",
					"/sales/quotes", "POST", "/api/admin/sales/quotes", 402),
			new PermissionSeed("sales:quote:update", "更新销售报价草稿", SystemPermissionType.ACTION, "sales",
					"/sales/quotes", "PUT", "/api/admin/sales/quotes/{id}", 403),
			new PermissionSeed("sales:quote:submit", "提交销售报价审批", SystemPermissionType.ACTION,
					"sales", "/sales/quotes", "POST", "/api/admin/sales/quotes/{id}/submit-approval", 404),
			new PermissionSeed("sales:quote:approve", "审批销售报价", SystemPermissionType.ACTION,
					"sales", "/platform/approvals", "POST", "/api/admin/approval-tasks/{id}/approve", 405),
			new PermissionSeed("sales:quote:cancel", "取消销售报价草稿", SystemPermissionType.ACTION,
					"sales", "/sales/quotes", "POST", "/api/admin/sales/quotes/{id}/cancel", 406),
			new PermissionSeed("sales:quote:convert", "销售报价转换", SystemPermissionType.ACTION,
					"sales", "/sales/quotes", "POST", "/api/admin/sales/quotes/{id}/convert-order", 407),
			new PermissionSeed("sales:quote:print", "打印销售报价", SystemPermissionType.ACTION,
					"sales", "/sales/quotes", "POST", "/api/admin/print-tasks", 408),
			new PermissionSeed("sales:quote:export", "导出销售报价", SystemPermissionType.ACTION,
					"sales", "/sales/quotes", "POST", "/api/admin/export-tasks", 409),
			new PermissionSeed("sales:delivery-plan:view", "查看销售交付计划", SystemPermissionType.ACTION,
					"sales", "/sales/delivery-plans", "GET", "/api/admin/sales/delivery-plans/**", 410),
			new PermissionSeed("sales:delivery-plan:manage", "管理销售交付计划", SystemPermissionType.ACTION,
					"sales", "/sales/delivery-plans", "PUT", "/api/admin/sales/orders/{id}/delivery-plans/**",
					411),
			new PermissionSeed("sales:order-change:view", "查看销售订单变更", SystemPermissionType.ACTION,
					"sales", "/sales/order-changes", "GET", "/api/admin/sales/order-changes/**", 412),
			new PermissionSeed("sales:order-change:create", "创建销售订单变更", SystemPermissionType.ACTION,
					"sales", "/sales/order-changes", "POST", "/api/admin/sales/orders/{id}/changes", 413),
			new PermissionSeed("sales:order-change:update", "更新销售订单变更", SystemPermissionType.ACTION,
					"sales", "/sales/order-changes", "PUT", "/api/admin/sales/order-changes/{id}", 414),
			new PermissionSeed("sales:order-change:submit", "提交销售订单变更审批", SystemPermissionType.ACTION,
					"sales", "/sales/order-changes", "POST",
					"/api/admin/sales/order-changes/{id}/submit-approval", 415),
			new PermissionSeed("sales:order-change:cancel", "取消销售订单变更草稿", SystemPermissionType.ACTION,
					"sales", "/sales/order-changes", "POST", "/api/admin/sales/order-changes/{id}/cancel", 416),
			new PermissionSeed("sales:order-change:approve", "审批销售订单变更", SystemPermissionType.ACTION,
					"sales", "/platform/approvals", "POST", "/api/admin/approval-tasks/{id}/approve", 417),
			new PermissionSeed("sales:credit:view", "查看客户信用占用", SystemPermissionType.ACTION,
					"sales", "/sales/credit", "GET", "/api/admin/sales/credit-profiles/**", 418),
			new PermissionSeed("sales:credit:manage", "维护客户信用档案", SystemPermissionType.ACTION,
					"sales", "/sales/credit", "PUT", "/api/admin/sales/credit-profiles/{id}", 419),
			new PermissionSeed("sales:credit:override-submit", "提交销售信用例外审批",
					SystemPermissionType.ACTION, "sales", "/sales/credit", "POST",
					"/api/admin/sales/orders/{id}/submit-credit-override", 420),
			new PermissionSeed("sales:credit:override-approve", "审批销售信用例外", SystemPermissionType.ACTION,
					"sales", "/platform/approvals", "POST", "/api/admin/approval-tasks/{id}/approve", 421),
			new PermissionSeed("sales:order:short-close-submit", "提交销售短交关闭审批",
					SystemPermissionType.ACTION, "sales", "/sales/orders", "POST",
					"/api/admin/sales/orders/{id}/submit-short-close", 422),
			new PermissionSeed("sales:order:short-close-approve", "审批销售短交关闭",
					SystemPermissionType.ACTION, "sales", "/platform/approvals", "POST",
					"/api/admin/approval-tasks/{id}/approve", 423),
			new PermissionSeed("sales:fulfillment:view", "查看项目销售履约", SystemPermissionType.ACTION,
					"sales", "/sales/projects", "GET", "/api/admin/sales-projects/{id}/fulfillment", 423),
			new PermissionSeed("sales:fulfillment:close", "关闭项目销售履约", SystemPermissionType.ACTION,
					"sales", "/sales/projects", "POST", "/api/admin/sales-projects/{id}/close-sales-fulfillment",
					424),
			new PermissionSeed("sales:effective-demand:view", "查看有效销售需求", SystemPermissionType.ACTION,
					"sales", "/sales/effective-demands", "GET", "/api/admin/sales/effective-demands/**", 425),
			new PermissionSeed("sales:effective-demand:export", "导出有效销售需求", SystemPermissionType.ACTION,
					"sales", "/sales/effective-demands", "POST", "/api/admin/export-tasks", 426),
			new PermissionSeed("sales:document:print", "打印销售单据", SystemPermissionType.ACTION,
					"sales", "/sales/quotes", "POST", "/api/admin/print-tasks", 427),
			new PermissionSeed("sales:document:export", "导出销售单据", SystemPermissionType.ACTION,
					"sales", "/sales/quotes", "POST", "/api/admin/export-tasks", 428),
			new PermissionSeed("sales:project", "销售项目", SystemPermissionType.MENU, "sales",
					"/sales/projects", null, null, 386),
			new PermissionSeed("sales:project:view", "查看销售项目", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "GET", "/api/admin/sales-projects/**", 387),
			new PermissionSeed("sales:project:create", "创建销售项目", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "POST", "/api/admin/sales-projects", 388),
			new PermissionSeed("sales:project:update", "更新销售项目", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "PUT", "/api/admin/sales-projects/{id}", 389),
			new PermissionSeed("sales:project:activate", "激活销售项目", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "PUT", "/api/admin/sales-projects/{id}/activate",
					390),
			new PermissionSeed("sales:project:close", "关闭销售项目", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "PUT", "/api/admin/sales-projects/{id}/close", 391),
			new PermissionSeed("sales:project:cancel", "取消销售项目", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "PUT", "/api/admin/sales-projects/{id}/cancel", 392),
			new PermissionSeed("sales:contract:view", "查看销售项目合同", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "GET", "/api/admin/sales-project-contracts/**", 393),
			new PermissionSeed("sales:contract:create", "创建销售项目合同", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "POST", "/api/admin/sales-projects/{id}/contracts",
					394),
			new PermissionSeed("sales:contract:update", "更新销售项目合同草稿", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "PUT", "/api/admin/sales-project-contracts/{id}",
					395),
			new PermissionSeed("sales:contract:activate", "激活销售项目合同", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "PUT",
					"/api/admin/sales-project-contracts/{id}/activate", 396),
			new PermissionSeed("sales:contract:activate-approve", "审批激活销售项目合同",
					SystemPermissionType.ACTION, "sales:project", "/sales/projects", "POST",
					"/api/admin/approval-tasks/{id}/approve", 400),
			new PermissionSeed("sales:contract:close", "关闭销售项目合同", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "PUT", "/api/admin/sales-project-contracts/{id}/close",
					397),
			new PermissionSeed("sales:contract:terminate", "终止销售项目合同", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "PUT",
					"/api/admin/sales-project-contracts/{id}/terminate", 398),
			new PermissionSeed("sales:contract:cancel", "取消销售项目合同草稿", SystemPermissionType.ACTION,
					"sales:project", "/sales/projects", "PUT",
					"/api/admin/sales-project-contracts/{id}/cancel", 399),
			new PermissionSeed("sales:shipment:view", "查看销售出库", SystemPermissionType.ACTION, "sales",
					"/sales/shipments", "GET", "/api/admin/sales/shipments/**", 377),
			new PermissionSeed("sales:shipment:create", "创建销售出库", SystemPermissionType.ACTION, "sales",
					"/sales/shipments", "POST", "/api/admin/sales/orders/{id}/shipments", 378),
			new PermissionSeed("sales:shipment:update", "更新销售出库草稿", SystemPermissionType.ACTION, "sales",
					"/sales/shipments", "PUT", "/api/admin/sales/shipments/{id}", 379),
			new PermissionSeed("sales:shipment:post", "过账销售出库", SystemPermissionType.ACTION, "sales",
					"/sales/shipments", "PUT", "/api/admin/sales/shipments/{id}/post", 380),
			new PermissionSeed("sales:return:view", "查看销售退货", SystemPermissionType.ACTION, "sales",
					"/sales/returns", "GET", "/api/admin/sales/returns/**", 381),
			new PermissionSeed("sales:return:create", "创建销售退货", SystemPermissionType.ACTION, "sales",
					"/sales/returns", "POST", "/api/admin/sales/returns", 382),
			new PermissionSeed("sales:return:update", "更新销售退货草稿", SystemPermissionType.ACTION, "sales",
					"/sales/returns", "PUT", "/api/admin/sales/returns/{id}", 383),
			new PermissionSeed("sales:return:post", "过账销售退货", SystemPermissionType.ACTION, "sales",
					"/sales/returns", "PUT", "/api/admin/sales/returns/{id}/post", 384),
			new PermissionSeed("sales:return:cancel", "取消销售退货草稿", SystemPermissionType.ACTION, "sales",
					"/sales/returns", "PUT", "/api/admin/sales/returns/{id}/cancel", 385),
			new PermissionSeed("production", "生产管理", SystemPermissionType.MENU, null, "/production/work-orders",
					null, null, 400),
			new PermissionSeed("production:work-order:view", "查看生产工单", SystemPermissionType.ACTION,
					"production", "/production/work-orders", "GET", "/api/admin/production/work-orders/**", 401),
			new PermissionSeed("production:work-order:create", "创建生产工单", SystemPermissionType.ACTION,
					"production", "/production/work-orders", "POST", "/api/admin/production/work-orders", 402),
			new PermissionSeed("production:work-order:update", "更新生产工单", SystemPermissionType.ACTION,
					"production", "/production/work-orders", "PUT", "/api/admin/production/work-orders/{id}", 403),
			new PermissionSeed("production:work-order:release", "发布生产工单", SystemPermissionType.ACTION,
					"production", "/production/work-orders", "PUT",
					"/api/admin/production/work-orders/{id}/release", 404),
			new PermissionSeed("production:work-order:complete", "完成生产工单", SystemPermissionType.ACTION,
					"production", "/production/work-orders", "PUT",
					"/api/admin/production/work-orders/{id}/complete", 405),
			new PermissionSeed("production:work-order:cancel", "取消生产工单", SystemPermissionType.ACTION,
					"production", "/production/work-orders", "PUT", "/api/admin/production/work-orders/{id}/cancel",
					406),
			new PermissionSeed("production:issue:view", "查看生产领料", SystemPermissionType.ACTION, "production",
					"/production/work-orders", "GET",
					"/api/admin/production/work-orders/{id}/material-issues/**", 407),
			new PermissionSeed("production:issue:create", "创建生产领料", SystemPermissionType.ACTION, "production",
					"/production/work-orders", "POST",
					"/api/admin/production/work-orders/{id}/material-issues", 408),
			new PermissionSeed("production:issue:update", "更新生产领料", SystemPermissionType.ACTION, "production",
					"/production/work-orders", "PUT",
					"/api/admin/production/work-orders/{id}/material-issues/{issueId}", 409),
			new PermissionSeed("production:issue:post", "过账生产领料", SystemPermissionType.ACTION, "production",
					"/production/work-orders", "PUT",
					"/api/admin/production/work-orders/{id}/material-issues/{issueId}/post", 410),
			new PermissionSeed("production:report:view", "查看生产报工", SystemPermissionType.ACTION, "production",
					"/production/work-orders", "GET", "/api/admin/production/work-orders/{id}/reports/**", 411),
			new PermissionSeed("production:report:create", "创建生产报工", SystemPermissionType.ACTION, "production",
					"/production/work-orders", "POST", "/api/admin/production/work-orders/{id}/reports", 412),
			new PermissionSeed("production:report:update", "更新生产报工", SystemPermissionType.ACTION, "production",
					"/production/work-orders", "PUT", "/api/admin/production/work-orders/{id}/reports/{reportId}",
					413),
			new PermissionSeed("production:report:post", "过账生产报工", SystemPermissionType.ACTION, "production",
					"/production/work-orders", "PUT",
					"/api/admin/production/work-orders/{id}/reports/{reportId}/post", 414),
			new PermissionSeed("production:receipt:view", "查看完工入库", SystemPermissionType.ACTION, "production",
					"/production/work-orders", "GET",
					"/api/admin/production/work-orders/{id}/completion-receipts/**", 415),
			new PermissionSeed("production:receipt:create", "创建完工入库", SystemPermissionType.ACTION,
					"production", "/production/work-orders", "POST",
					"/api/admin/production/work-orders/{id}/completion-receipts", 416),
			new PermissionSeed("production:receipt:update", "更新完工入库", SystemPermissionType.ACTION,
					"production", "/production/work-orders", "PUT",
					"/api/admin/production/work-orders/{id}/completion-receipts/{receiptId}", 417),
			new PermissionSeed("production:receipt:post", "过账完工入库", SystemPermissionType.ACTION, "production",
					"/production/work-orders", "PUT",
					"/api/admin/production/work-orders/{id}/completion-receipts/{receiptId}/post", 418),
			new PermissionSeed("production:material-return:view", "查看生产退料", SystemPermissionType.ACTION,
					"production", "/production/material-returns", "GET",
					"/api/admin/production/material-returns/**", 419),
			new PermissionSeed("production:material-return:create", "创建生产退料", SystemPermissionType.ACTION,
					"production", "/production/material-returns", "POST",
					"/api/admin/production/material-returns", 420),
			new PermissionSeed("production:material-return:update", "更新生产退料草稿", SystemPermissionType.ACTION,
					"production", "/production/material-returns", "PUT",
					"/api/admin/production/material-returns/{id}", 421),
			new PermissionSeed("production:material-return:post", "过账生产退料", SystemPermissionType.ACTION,
					"production", "/production/material-returns", "PUT",
					"/api/admin/production/material-returns/{id}/post", 422),
			new PermissionSeed("production:material-return:cancel", "取消生产退料草稿", SystemPermissionType.ACTION,
					"production", "/production/material-returns", "PUT",
					"/api/admin/production/material-returns/{id}/cancel", 423),
			new PermissionSeed("production:material-supplement:view", "查看生产补料", SystemPermissionType.ACTION,
					"production", "/production/material-supplements", "GET",
					"/api/admin/production/material-supplements/**", 424),
			new PermissionSeed("production:material-supplement:create", "创建生产补料", SystemPermissionType.ACTION,
					"production", "/production/material-supplements", "POST",
					"/api/admin/production/material-supplements", 425),
			new PermissionSeed("production:material-supplement:update", "更新生产补料草稿",
					SystemPermissionType.ACTION, "production", "/production/material-supplements", "PUT",
					"/api/admin/production/material-supplements/{id}", 426),
			new PermissionSeed("production:material-supplement:post", "过账生产补料", SystemPermissionType.ACTION,
					"production", "/production/material-supplements", "PUT",
					"/api/admin/production/material-supplements/{id}/post", 427),
			new PermissionSeed("production:material-supplement:cancel", "取消生产补料草稿",
					SystemPermissionType.ACTION, "production", "/production/material-supplements", "PUT",
					"/api/admin/production/material-supplements/{id}/cancel", 428),
			new PermissionSeed("production:outsourcing:view", "查看外协订单", SystemPermissionType.ACTION, "production",
					"/production/outsourcing-orders", "GET", "/api/admin/production/outsourcing-orders/**", 429),
			new PermissionSeed("production:outsourcing:create", "创建外协订单", SystemPermissionType.ACTION,
					"production", "/production/outsourcing-orders", "POST",
					"/api/admin/production/outsourcing-orders", 430),
			new PermissionSeed("production:outsourcing:update", "更新外协订单", SystemPermissionType.ACTION,
					"production", "/production/outsourcing-orders", "PUT",
					"/api/admin/production/outsourcing-orders/{id}", 431),
			new PermissionSeed("production:outsourcing:release", "发布外协订单", SystemPermissionType.ACTION,
					"production", "/production/outsourcing-orders", "PUT",
					"/api/admin/production/outsourcing-orders/{id}/release", 432),
			new PermissionSeed("production:outsourcing:close", "关闭外协订单", SystemPermissionType.ACTION,
					"production", "/production/outsourcing-orders", "PUT",
					"/api/admin/production/outsourcing-orders/{id}/close", 433),
			new PermissionSeed("production:outsourcing:cancel", "取消外协订单", SystemPermissionType.ACTION,
					"production", "/production/outsourcing-orders", "PUT",
					"/api/admin/production/outsourcing-orders/{id}/cancel", 434),
			new PermissionSeed("production:outsourcing-issue:view", "查看外协发料", SystemPermissionType.ACTION,
					"production", "/production/outsourcing-orders", "GET",
					"/api/admin/production/outsourcing-orders/{id}/material-issues/**", 435),
			new PermissionSeed("production:outsourcing-issue:create", "创建外协发料", SystemPermissionType.ACTION,
					"production", "/production/outsourcing-orders", "POST",
					"/api/admin/production/outsourcing-orders/{id}/material-issues", 436),
			new PermissionSeed("production:outsourcing-issue:update", "更新外协发料草稿",
					SystemPermissionType.ACTION, "production", "/production/outsourcing-orders", "PUT",
					"/api/admin/production/outsourcing-orders/{id}/material-issues/{issueId}", 437),
			new PermissionSeed("production:outsourcing-issue:post", "过账外协发料", SystemPermissionType.ACTION,
					"production", "/production/outsourcing-orders", "PUT",
					"/api/admin/production/outsourcing-orders/{id}/material-issues/{issueId}/post", 438),
			new PermissionSeed("production:outsourcing-issue:cancel", "取消外协发料草稿",
					SystemPermissionType.ACTION, "production", "/production/outsourcing-orders", "PUT",
					"/api/admin/production/outsourcing-orders/{id}/material-issues/{issueId}/cancel", 439),
			new PermissionSeed("production:outsourcing-receipt:view", "查看外协收货", SystemPermissionType.ACTION,
					"production", "/production/outsourcing-orders", "GET",
					"/api/admin/production/outsourcing-orders/{id}/receipts/**", 440),
			new PermissionSeed("production:outsourcing-receipt:create", "创建外协收货", SystemPermissionType.ACTION,
					"production", "/production/outsourcing-orders", "POST",
					"/api/admin/production/outsourcing-orders/{id}/receipts", 441),
			new PermissionSeed("production:outsourcing-receipt:update", "更新外协收货草稿",
					SystemPermissionType.ACTION, "production", "/production/outsourcing-orders", "PUT",
					"/api/admin/production/outsourcing-orders/{id}/receipts/{receiptId}", 442),
			new PermissionSeed("production:outsourcing-receipt:post", "过账外协收货", SystemPermissionType.ACTION,
					"production", "/production/outsourcing-orders", "PUT",
					"/api/admin/production/outsourcing-orders/{id}/receipts/{receiptId}/post", 443),
			new PermissionSeed("production:outsourcing-receipt:cancel", "取消外协收货草稿",
					SystemPermissionType.ACTION, "production", "/production/outsourcing-orders", "PUT",
					"/api/admin/production/outsourcing-orders/{id}/receipts/{receiptId}/cancel", 444),
			new PermissionSeed("cost", "成本管理", SystemPermissionType.MENU, null, "/cost/records", null, null,
					500),
			new PermissionSeed("cost:record:view", "查看成本记录", SystemPermissionType.ACTION, "cost",
					"/cost/records", "GET", "/api/admin/cost/**", 501),
			new PermissionSeed("cost:record:create", "创建成本记录", SystemPermissionType.ACTION, "cost",
					"/cost/records", "POST", "/api/admin/cost/records", 502),
			new PermissionSeed("cost:record:update", "更新手工成本记录", SystemPermissionType.ACTION, "cost",
					"/cost/records", "PUT", "/api/admin/cost/records/{id}", 503),
			new PermissionSeed("cost:project-cost", "项目成本核算", SystemPermissionType.MENU, "cost",
					"/cost/project-costs", null, null, 510),
			new PermissionSeed("cost:project-cost:view", "查看项目成本", SystemPermissionType.ACTION,
					"cost:project-cost", "/cost/project-costs", "GET", "/api/admin/cost/project-costs/**",
					511),
			new PermissionSeed("cost:project-cost:source-view", "查看项目成本来源", SystemPermissionType.ACTION,
					"cost:project-cost", "/cost/project-costs", "GET",
					"/api/admin/cost/project-cost-calculations/{id}/sources", 512),
			new PermissionSeed("cost:project-cost:amount-view", "查看项目成本金额", SystemPermissionType.ACTION,
					"cost:project-cost", "/cost/project-costs", null, null, 513),
			new PermissionSeed("cost:project-cost:calculate", "计算项目成本", SystemPermissionType.ACTION,
					"cost:project-cost", "/cost/project-costs", "POST",
					"/api/admin/cost/project-costs/projects/{projectId}/calculations", 514),
			new PermissionSeed("cost:project-cost:confirm", "确认项目成本", SystemPermissionType.ACTION,
					"cost:project-cost", "/cost/project-costs", "PUT",
					"/api/admin/cost/project-cost-calculations/{id}/confirm", 515),
			new PermissionSeed("cost:project-cost:cancel", "取消项目成本计算", SystemPermissionType.ACTION,
					"cost:project-cost", "/cost/project-costs", "PUT",
					"/api/admin/cost/project-cost-calculations/{id}/cancel", 516),
			new PermissionSeed("cost:project-cost-adjustment", "项目成本调整", SystemPermissionType.MENU, "cost",
					"/cost/project-cost-adjustments", null, null, 520),
			new PermissionSeed("cost:project-cost-adjustment:view", "查看项目成本调整",
					SystemPermissionType.ACTION, "cost:project-cost-adjustment", "/cost/project-cost-adjustments",
					"GET", "/api/admin/cost/project-cost-adjustments/**", 521),
			new PermissionSeed("cost:project-cost-adjustment:create", "创建项目成本调整",
					SystemPermissionType.ACTION, "cost:project-cost-adjustment", "/cost/project-cost-adjustments",
					"POST", "/api/admin/cost/project-cost-adjustments", 522),
			new PermissionSeed("cost:project-cost-adjustment:update", "更新项目成本调整",
					SystemPermissionType.ACTION, "cost:project-cost-adjustment", "/cost/project-cost-adjustments",
					"PUT", "/api/admin/cost/project-cost-adjustments/{id}", 523),
			new PermissionSeed("cost:project-cost-adjustment:submit", "提交项目成本调整审批",
					SystemPermissionType.ACTION, "cost:project-cost-adjustment", "/cost/project-cost-adjustments",
					"PUT", "/api/admin/cost/project-cost-adjustments/{id}/submit", 524),
			new PermissionSeed("cost:project-cost-adjustment:cancel", "取消项目成本调整",
					SystemPermissionType.ACTION, "cost:project-cost-adjustment", "/cost/project-cost-adjustments",
					"PUT", "/api/admin/cost/project-cost-adjustments/{id}/cancel", 525),
			new PermissionSeed("cost:project-cost-variance:view", "查看项目成本差异",
					SystemPermissionType.ACTION, "cost:project-cost", "/cost/project-costs", "GET",
					"/api/admin/cost/project-cost-variances/**", 526),
			new PermissionSeed("finance", "财务往来", SystemPermissionType.MENU, null, "/finance", null, null,
					600),
			new PermissionSeed("finance:receivable:view", "查看应收", SystemPermissionType.ACTION, "finance",
					"/finance/receivables", "GET", "/api/admin/finance/receivables/**", 601),
			new PermissionSeed("finance:receivable:create", "生成应收", SystemPermissionType.ACTION, "finance",
					"/finance/receivables", "POST", "/api/admin/finance/receivables", 602),
			new PermissionSeed("finance:receivable:update", "更新应收草稿", SystemPermissionType.ACTION, "finance",
					"/finance/receivables", "PUT", "/api/admin/finance/receivables/{id}", 603),
			new PermissionSeed("finance:receivable:confirm", "确认应收", SystemPermissionType.ACTION, "finance",
					"/finance/receivables", "PUT", "/api/admin/finance/receivables/{id}/confirm", 604),
			new PermissionSeed("finance:receivable:cancel", "取消应收", SystemPermissionType.ACTION, "finance",
					"/finance/receivables", "PUT", "/api/admin/finance/receivables/{id}/cancel", 605),
			new PermissionSeed("finance:receivable:close", "关闭应收", SystemPermissionType.ACTION, "finance",
					"/finance/receivables", "PUT", "/api/admin/finance/receivables/{id}/close", 606),
			new PermissionSeed("finance:receipt:view", "查看收款", SystemPermissionType.ACTION, "finance",
					"/finance/receipts", "GET", "/api/admin/finance/receipts/**", 607),
			new PermissionSeed("finance:receipt:create", "创建收款草稿", SystemPermissionType.ACTION, "finance",
					"/finance/receipts", "POST", "/api/admin/finance/receivables/{id}/receipts", 608),
			new PermissionSeed("finance:receipt:update", "更新收款草稿", SystemPermissionType.ACTION, "finance",
					"/finance/receipts", "PUT", "/api/admin/finance/receipts/{id}", 609),
			new PermissionSeed("finance:receipt:post", "过账收款", SystemPermissionType.ACTION, "finance",
					"/finance/receipts", "PUT", "/api/admin/finance/receipts/{id}/post", 610),
			new PermissionSeed("finance:receipt:cancel", "取消收款草稿", SystemPermissionType.ACTION, "finance",
					"/finance/receipts", "PUT", "/api/admin/finance/receipts/{id}/cancel", 611),
			new PermissionSeed("finance:payable:view", "查看应付", SystemPermissionType.ACTION, "finance",
					"/finance/payables", "GET", "/api/admin/finance/payables/**", 612),
			new PermissionSeed("finance:payable:create", "生成应付", SystemPermissionType.ACTION, "finance",
					"/finance/payables", "POST", "/api/admin/finance/payables", 613),
			new PermissionSeed("finance:payable:update", "更新应付草稿", SystemPermissionType.ACTION, "finance",
					"/finance/payables", "PUT", "/api/admin/finance/payables/{id}", 614),
			new PermissionSeed("finance:payable:confirm", "确认应付", SystemPermissionType.ACTION, "finance",
					"/finance/payables", "PUT", "/api/admin/finance/payables/{id}/confirm", 615),
			new PermissionSeed("finance:payable:cancel", "取消应付", SystemPermissionType.ACTION, "finance",
					"/finance/payables", "PUT", "/api/admin/finance/payables/{id}/cancel", 616),
			new PermissionSeed("finance:payable:close", "关闭应付", SystemPermissionType.ACTION, "finance",
					"/finance/payables", "PUT", "/api/admin/finance/payables/{id}/close", 617),
			new PermissionSeed("finance:payment:view", "查看付款", SystemPermissionType.ACTION, "finance",
					"/finance/payments", "GET", "/api/admin/finance/payments/**", 618),
			new PermissionSeed("finance:payment:create", "创建付款草稿", SystemPermissionType.ACTION, "finance",
					"/finance/payments", "POST", "/api/admin/finance/payables/{id}/payments", 619),
			new PermissionSeed("finance:payment:update", "更新付款草稿", SystemPermissionType.ACTION, "finance",
					"/finance/payments", "PUT", "/api/admin/finance/payments/{id}", 620),
			new PermissionSeed("finance:payment:post", "过账付款", SystemPermissionType.ACTION, "finance",
					"/finance/payments", "PUT", "/api/admin/finance/payments/{id}/post", 621),
			new PermissionSeed("finance:payment:cancel", "取消付款草稿", SystemPermissionType.ACTION, "finance",
					"/finance/payments", "PUT", "/api/admin/finance/payments/{id}/cancel", 622),
			new PermissionSeed("finance:settlement-adjustment:view", "查看往来冲减", SystemPermissionType.ACTION,
					"finance", "/finance/settlement-adjustments", "GET",
					"/api/admin/finance/settlement-adjustments/**", 623),
			new PermissionSeed("finance:settlement-adjustment:create", "创建往来冲减", SystemPermissionType.ACTION,
					"finance", "/finance/settlement-adjustments", "POST",
					"/api/admin/finance/settlement-adjustments", 624),
			new PermissionSeed("finance:settlement-adjustment:update", "更新往来冲减草稿",
					SystemPermissionType.ACTION, "finance", "/finance/settlement-adjustments", "PUT",
					"/api/admin/finance/settlement-adjustments/{id}", 625),
			new PermissionSeed("finance:settlement-adjustment:post", "过账往来冲减", SystemPermissionType.ACTION,
					"finance", "/finance/settlement-adjustments", "PUT",
					"/api/admin/finance/settlement-adjustments/{id}/post", 626),
			new PermissionSeed("finance:settlement-adjustment:cancel", "取消往来冲减草稿",
					SystemPermissionType.ACTION, "finance", "/finance/settlement-adjustments", "PUT",
					"/api/admin/finance/settlement-adjustments/{id}/cancel", 627),
			new PermissionSeed("finance:sales-invoice:view", "查看销售发票", SystemPermissionType.ACTION,
					"finance", "/finance/sales-invoices", "GET", "/api/admin/finance/sales-invoices/**", 628),
			new PermissionSeed("finance:sales-invoice:create", "创建销售发票", SystemPermissionType.ACTION,
					"finance", "/finance/sales-invoices", "POST", "/api/admin/finance/sales-invoices", 629),
			new PermissionSeed("finance:sales-invoice:update", "更新销售发票草稿", SystemPermissionType.ACTION,
					"finance", "/finance/sales-invoices", "PUT", "/api/admin/finance/sales-invoices/{id}", 630),
			new PermissionSeed("finance:sales-invoice:confirm", "确认销售发票", SystemPermissionType.ACTION,
					"finance", "/finance/sales-invoices", "PUT",
					"/api/admin/finance/sales-invoices/{id}/confirm", 631),
			new PermissionSeed("finance:sales-invoice:cancel", "取消销售发票", SystemPermissionType.ACTION,
					"finance", "/finance/sales-invoices", "PUT",
					"/api/admin/finance/sales-invoices/{id}/cancel", 632),
			new PermissionSeed("finance:purchase-invoice:view", "查看采购发票", SystemPermissionType.ACTION,
					"finance", "/finance/purchase-invoices", "GET", "/api/admin/finance/purchase-invoices/**",
					633),
			new PermissionSeed("finance:purchase-invoice:create", "创建采购发票", SystemPermissionType.ACTION,
					"finance", "/finance/purchase-invoices", "POST", "/api/admin/finance/purchase-invoices", 634),
			new PermissionSeed("finance:purchase-invoice:update", "更新采购发票草稿", SystemPermissionType.ACTION,
					"finance", "/finance/purchase-invoices", "PUT", "/api/admin/finance/purchase-invoices/{id}",
					635),
			new PermissionSeed("finance:purchase-invoice:match", "执行采购发票匹配", SystemPermissionType.ACTION,
					"finance", "/finance/purchase-invoices", "PUT",
					"/api/admin/finance/purchase-invoices/{id}/match", 636),
			new PermissionSeed("finance:purchase-invoice:confirm", "确认采购发票", SystemPermissionType.ACTION,
					"finance", "/finance/purchase-invoices", "PUT",
					"/api/admin/finance/purchase-invoices/{id}/confirm", 637),
			new PermissionSeed("finance:purchase-invoice:cancel", "取消采购发票", SystemPermissionType.ACTION,
					"finance", "/finance/purchase-invoices", "PUT",
					"/api/admin/finance/purchase-invoices/{id}/cancel", 638),
			new PermissionSeed("finance:expense:view", "查看费用单", SystemPermissionType.ACTION, "finance",
					"/finance/expenses", "GET", "/api/admin/finance/expenses/**", 639),
			new PermissionSeed("finance:expense:create", "创建费用单", SystemPermissionType.ACTION, "finance",
					"/finance/expenses", "POST", "/api/admin/finance/expenses", 640),
			new PermissionSeed("finance:expense:update", "更新费用单草稿", SystemPermissionType.ACTION,
					"finance", "/finance/expenses", "PUT", "/api/admin/finance/expenses/{id}", 641),
			new PermissionSeed("finance:expense:confirm", "确认费用单", SystemPermissionType.ACTION, "finance",
					"/finance/expenses", "PUT", "/api/admin/finance/expenses/{id}/confirm", 642),
			new PermissionSeed("finance:expense:cancel", "取消费用单", SystemPermissionType.ACTION, "finance",
					"/finance/expenses", "PUT", "/api/admin/finance/expenses/{id}/cancel", 643),
			new PermissionSeed("finance:advance-receipt:view", "查看预收款", SystemPermissionType.ACTION,
					"finance", "/finance/advance-receipts", "GET", "/api/admin/finance/advance-receipts/**",
					644),
			new PermissionSeed("finance:advance-receipt:create", "创建预收款", SystemPermissionType.ACTION,
					"finance", "/finance/advance-receipts", "POST", "/api/admin/finance/advance-receipts", 645),
			new PermissionSeed("finance:advance-receipt:update", "更新预收款草稿", SystemPermissionType.ACTION,
					"finance", "/finance/advance-receipts", "PUT", "/api/admin/finance/advance-receipts/{id}",
					646),
			new PermissionSeed("finance:advance-receipt:post", "过账预收款", SystemPermissionType.ACTION,
					"finance", "/finance/advance-receipts", "PUT",
					"/api/admin/finance/advance-receipts/{id}/post", 647),
			new PermissionSeed("finance:advance-receipt:cancel", "取消预收款草稿", SystemPermissionType.ACTION,
					"finance", "/finance/advance-receipts", "PUT",
					"/api/admin/finance/advance-receipts/{id}/cancel", 648),
			new PermissionSeed("finance:prepayment:view", "查看预付款", SystemPermissionType.ACTION, "finance",
					"/finance/prepayments", "GET", "/api/admin/finance/prepayments/**", 649),
			new PermissionSeed("finance:prepayment:create", "创建预付款", SystemPermissionType.ACTION, "finance",
					"/finance/prepayments", "POST", "/api/admin/finance/prepayments", 650),
			new PermissionSeed("finance:prepayment:update", "更新预付款草稿", SystemPermissionType.ACTION,
					"finance", "/finance/prepayments", "PUT", "/api/admin/finance/prepayments/{id}", 651),
			new PermissionSeed("finance:prepayment:post", "过账预付款", SystemPermissionType.ACTION, "finance",
					"/finance/prepayments", "PUT", "/api/admin/finance/prepayments/{id}/post", 652),
			new PermissionSeed("finance:prepayment:cancel", "取消预付款草稿", SystemPermissionType.ACTION,
					"finance", "/finance/prepayments", "PUT", "/api/admin/finance/prepayments/{id}/cancel", 653),
			new PermissionSeed("finance:settlement-allocation:view", "查看多目标核销",
					SystemPermissionType.ACTION, "finance", "/finance/settlement-workbench", "GET",
					"/api/admin/finance/settlement-workbench/**", 654),
			new PermissionSeed("finance:settlement-allocation:create", "创建多目标核销",
					SystemPermissionType.ACTION, "finance", "/finance/settlement-workbench", "POST",
					"/api/admin/finance/settlement-workbench/allocations", 655),
			new PermissionSeed("finance:settlement-allocation:update", "更新多目标核销草稿",
					SystemPermissionType.ACTION, "finance", "/finance/settlement-workbench", "PUT",
					"/api/admin/finance/settlement-workbench/allocations/{id}", 656),
			new PermissionSeed("finance:settlement-allocation:post", "过账多目标核销",
					SystemPermissionType.ACTION, "finance", "/finance/settlement-workbench", "PUT",
					"/api/admin/finance/settlement-workbench/allocations/{id}/post", 657),
			new PermissionSeed("finance:settlement-allocation:cancel", "取消多目标核销草稿",
					SystemPermissionType.ACTION, "finance", "/finance/settlement-workbench", "PUT",
					"/api/admin/finance/settlement-workbench/allocations/{id}/cancel", 658),
			new PermissionSeed("finance:voucher-draft:view", "查看凭证草稿", SystemPermissionType.ACTION,
					"finance", "/finance/voucher-drafts", "GET", "/api/admin/finance/voucher-drafts/**", 659),
			new PermissionSeed("finance:voucher-draft:generate", "生成凭证草稿", SystemPermissionType.ACTION,
					"finance", "/finance/voucher-drafts", "POST",
					"/api/admin/finance/voucher-drafts/generate", 660),
			new PermissionSeed("finance:voucher-draft:ready", "凭证草稿置为就绪", SystemPermissionType.ACTION,
					"finance", "/finance/voucher-drafts", "PUT", "/api/admin/finance/voucher-drafts/{id}/ready",
					661),
			new PermissionSeed("finance:voucher-draft:cancel", "取消凭证草稿", SystemPermissionType.ACTION,
					"finance", "/finance/voucher-drafts", "PUT",
					"/api/admin/finance/voucher-drafts/{id}/cancel", 662),
			new PermissionSeed("finance:settlement-sensitive:view", "查看结算敏感资料",
					SystemPermissionType.ACTION, "finance", "/finance", null, null, 663),
			new PermissionSeed("finance:settlement-sensitive:update", "维护结算敏感资料",
					SystemPermissionType.ACTION, "finance", "/finance", null, null, 664),
			new PermissionSeed("planning", "计划管理", SystemPermissionType.MENU, null,
					"/planning/material-requirements", null, null, 650),
			new PermissionSeed("planning:material-requirement", "订单缺料与供给建议", SystemPermissionType.MENU,
					"planning", "/planning/material-requirements", null, null, 651),
			new PermissionSeed("planning:material-requirement:view", "查看订单缺料与供给建议",
					SystemPermissionType.ACTION, "planning:material-requirement", "/planning/material-requirements",
					"GET", "/api/admin/planning/material-requirement-runs/**", 652),
			new PermissionSeed("planning:material-requirement:calculate", "计算订单缺料与供给建议",
					SystemPermissionType.ACTION, "planning:material-requirement", "/planning/material-requirements",
					"POST", "/api/admin/planning/material-requirement-runs/**", 653),
			new PermissionSeed("planning:material-requirement:manage-suggestion", "确认或驳回缺料建议",
					SystemPermissionType.ACTION, "planning:material-requirement", "/planning/material-requirements",
					"PUT", "/api/admin/planning/material-requirement-suggestions/{id}/**", 654),
			new PermissionSeed("planning:material-requirement:convert-requisition", "缺料建议转采购请购",
					SystemPermissionType.ACTION, "planning:material-requirement", "/planning/material-requirements",
					"POST", "/api/admin/planning/material-requirement-suggestions/{id}/convert-requisition", 655),
			new PermissionSeed("planning:material-requirement:convert-production", "缺料建议转生产工单",
					SystemPermissionType.ACTION, "planning:material-requirement", "/planning/material-requirements",
					"POST", "/api/admin/planning/material-requirement-suggestions/{id}/convert-work-order", 657),
			new PermissionSeed("planning:material-requirement:convert-outsourcing", "缺料建议转外协订单",
					SystemPermissionType.ACTION, "planning:material-requirement", "/planning/material-requirements",
					"POST", "/api/admin/planning/material-requirement-suggestions/{id}/convert-outsourcing-order",
					658),
			new PermissionSeed("planning:material-requirement:export", "导出订单缺料与供给建议",
					SystemPermissionType.ACTION, "planning:material-requirement", "/planning/material-requirements",
					"POST", "/api/admin/export-tasks", 656),
			new PermissionSeed("quality", "质量管理", SystemPermissionType.MENU, null, "/quality/inspections", null,
					null, 700),
			new PermissionSeed("quality:inspection:view", "查看质量确认", SystemPermissionType.ACTION, "quality",
					"/quality/inspections", "GET", "/api/admin/quality/inspections/**", 701),
			new PermissionSeed("quality:inspection:process", "处理质量确认", SystemPermissionType.ACTION, "quality",
					"/quality/inspections", "POST", "/api/admin/quality/inspections/{id}/process", 702),
			new PermissionSeed("quality:status:freeze", "冻结库存质量状态", SystemPermissionType.ACTION, "quality",
					"/quality/inspections", "POST", "/api/admin/inventory/quality-transfers/freeze", 703),
			new PermissionSeed("quality:status:unfreeze", "解冻库存质量状态", SystemPermissionType.ACTION, "quality",
					"/quality/inspections", "POST", "/api/admin/inventory/quality-transfers/unfreeze", 704),
			new PermissionSeed("report", "经营报表", SystemPermissionType.MENU, null, "/reports", null, null,
					700),
			new PermissionSeed("report:overview:view", "查看经营概览", SystemPermissionType.ACTION, "report",
					"/reports/overview", "GET", "/api/admin/reports/overview", 701),
			new PermissionSeed("report:sales:view", "查看销售经营报表", SystemPermissionType.ACTION, "report",
					"/reports/sales", "GET", "/api/admin/reports/sales-summary/**", 702),
			new PermissionSeed("report:procurement:view", "查看采购经营报表", SystemPermissionType.ACTION,
					"report", "/reports/procurement", "GET",
					"/api/admin/reports/procurement-summary/**", 703),
			new PermissionSeed("report:inventory:view", "查看库存收发存报表", SystemPermissionType.ACTION,
					"report", "/reports/inventory", "GET",
					"/api/admin/reports/inventory-stock-flow/**", 704),
			new PermissionSeed("report:production:view", "查看生产执行报表", SystemPermissionType.ACTION,
					"report", "/reports/production", "GET",
					"/api/admin/reports/production-execution/**", 705),
			new PermissionSeed("report:cost:view", "查看成本归集报表", SystemPermissionType.ACTION, "report",
					"/reports/cost", "GET", "/api/admin/reports/cost-collection/**", 706),
			new PermissionSeed("report:settlement:view", "查看往来收付报表", SystemPermissionType.ACTION,
					"report", "/reports/settlement", "GET",
					"/api/admin/reports/settlement-summary/**", 707),
			new PermissionSeed("report:exception:view", "查看经营异常清单", SystemPermissionType.ACTION,
					"report", "/reports/exceptions", "GET", "/api/admin/reports/exceptions/**", 708),
			new PermissionSeed("reversal", "退货退款与反冲", SystemPermissionType.MENU, null, "/reversal", null, null,
					800),
			new PermissionSeed("business:reversal:view", "查看业务反冲追溯", SystemPermissionType.ACTION,
					"reversal", "/reversal/traces", "GET", "/api/admin/reversal-traces", 801),
			new PermissionSeed("gl", "会计核算", SystemPermissionType.MENU, null, "/gl", null, null, 850),
			new PermissionSeed("gl:account", "会计科目", SystemPermissionType.MENU, "gl", "/gl/accounts", null,
					null, 851),
			new PermissionSeed("gl:auxiliary", "辅助核算", SystemPermissionType.MENU, "gl", "/gl/auxiliaries",
					null, null, 852),
			new PermissionSeed("gl:period", "会计期间", SystemPermissionType.MENU, "gl", "/gl/accounting-periods",
					null, null, 853),
			new PermissionSeed("gl:rule", "制证规则", SystemPermissionType.MENU, "gl", "/gl/posting-rules",
					null, null, 854),
			new PermissionSeed("gl:voucher", "正式凭证", SystemPermissionType.MENU, "gl", "/gl/vouchers", null,
					null, 855),
			new PermissionSeed("gl:ledger", "总账明细账", SystemPermissionType.MENU, "gl",
					"/gl/ledgers/general", null, null, 856),
			new PermissionSeed("gl:balance", "余额与试算", SystemPermissionType.MENU, "gl",
					"/gl/trial-balance", null, null, 857),
			new PermissionSeed("gl:account:view", "查看会计科目", SystemPermissionType.ACTION, "gl:account",
					"/gl/accounts", "GET", "/api/admin/gl/accounts/**", 858),
			new PermissionSeed("gl:account:create", "创建会计科目", SystemPermissionType.ACTION, "gl:account",
					"/gl/accounts", "POST", "/api/admin/gl/accounts", 859),
			new PermissionSeed("gl:account:update", "维护会计科目", SystemPermissionType.ACTION, "gl:account",
					"/gl/accounts", "PUT", "/api/admin/gl/accounts/{id}", 860),
			new PermissionSeed("gl:account:disable", "停用会计科目", SystemPermissionType.ACTION,
					"gl:account", "/gl/accounts", "POST", "/api/admin/gl/accounts/{id}/disable", 861),
			new PermissionSeed("gl:auxiliary:view", "查看辅助核算", SystemPermissionType.ACTION,
					"gl:auxiliary", "/gl/auxiliaries", "GET", "/api/admin/gl/aux-dimensions/**", 862),
			new PermissionSeed("gl:auxiliary:manage", "维护辅助核算", SystemPermissionType.ACTION,
					"gl:auxiliary", "/gl/auxiliaries", null, "/api/admin/gl/aux-dimensions/**", 863),
			new PermissionSeed("gl:period:view", "查看会计期间", SystemPermissionType.ACTION, "gl:period",
					"/gl/accounting-periods", "GET", "/api/admin/gl/accounting-periods/**", 864),
			new PermissionSeed("gl:period:initialize", "启用总账", SystemPermissionType.ACTION, "gl:period",
					"/gl/accounting-periods", "POST", "/api/admin/gl/ledger/initialize", 865),
			new PermissionSeed("gl:period:create", "新增会计期间", SystemPermissionType.ACTION, "gl:period",
					"/gl/accounting-periods", "POST", "/api/admin/gl/accounting-periods", 866),
			new PermissionSeed("gl:rule:view", "查看制证规则", SystemPermissionType.ACTION, "gl:rule",
					"/gl/posting-rules", "GET", "/api/admin/gl/posting-rules/**", 867),
			new PermissionSeed("gl:rule:manage", "维护制证规则", SystemPermissionType.ACTION, "gl:rule",
					"/gl/posting-rules", null, "/api/admin/gl/posting-rules/**", 868),
			new PermissionSeed("gl:voucher:view", "查看正式凭证", SystemPermissionType.ACTION, "gl:voucher",
					"/gl/vouchers", "GET", "/api/admin/gl/vouchers/**", 869),
			new PermissionSeed("gl:voucher:create", "创建正式凭证", SystemPermissionType.ACTION, "gl:voucher",
					"/gl/vouchers", "POST", "/api/admin/gl/vouchers", 870),
			new PermissionSeed("gl:voucher:update", "维护正式凭证草稿", SystemPermissionType.ACTION,
					"gl:voucher", "/gl/vouchers", "PUT", "/api/admin/gl/vouchers/{id}", 871),
			new PermissionSeed("gl:voucher:convert", "从往来草稿生成正式凭证", SystemPermissionType.ACTION,
					"gl:voucher", "/gl/vouchers", "POST", "/api/admin/gl/vouchers/from-finance-draft/{id}",
					872),
			new PermissionSeed("gl:voucher:submit", "提交正式凭证审批", SystemPermissionType.ACTION,
					"gl:voucher", "/gl/vouchers", "POST", "/api/admin/gl/vouchers/{id}/submit", 873),
			new PermissionSeed("gl:voucher:cancel", "取消正式凭证草稿", SystemPermissionType.ACTION,
					"gl:voucher", "/gl/vouchers", "POST", "/api/admin/gl/vouchers/{id}/cancel", 874),
			new PermissionSeed("gl:voucher:reverse", "发起正式凭证冲销", SystemPermissionType.ACTION,
					"gl:voucher", "/gl/vouchers", "POST", "/api/admin/gl/vouchers/{id}/reversals", 875),
			new PermissionSeed("gl:voucher:approve-post", "通过并记账正式凭证", SystemPermissionType.ACTION,
					"gl:voucher", "/platform/tasks", "POST", "/api/admin/approval-tasks/{id}/approve", 876),
			new PermissionSeed("gl:ledger:view", "查看总账和明细账", SystemPermissionType.ACTION,
					"gl:ledger", "/gl/ledgers/general", "GET", "/api/admin/gl/ledgers/**", 877),
			new PermissionSeed("gl:balance:view", "查看科目余额和试算平衡", SystemPermissionType.ACTION,
					"gl:balance", "/gl/trial-balance", "GET", "/api/admin/gl/trial-balance", 878),
			new PermissionSeed("gl:amount:view", "查看总账金额", SystemPermissionType.ACTION, "gl:balance",
					"/gl/trial-balance", null, null, 879),
			new PermissionSeed("gl:source:view", "查看总账来源", SystemPermissionType.ACTION, "gl:voucher",
					"/gl/vouchers", null, null, 880),
			new PermissionSeed("financial-close", "财务结账", SystemPermissionType.MENU, "gl",
					"/gl/financial-close", null, null, 881),
			new PermissionSeed("financial-close:period", "财务结账期间", SystemPermissionType.MENU,
					"financial-close", "/gl/financial-close", null, null, 882),
			new PermissionSeed("financial-close:profit-loss", "期末损益结转", SystemPermissionType.MENU,
					"financial-close", "/gl/profit-loss-carryforward", null, null, 883),
			new PermissionSeed("financial-close:bank-account", "银行账户", SystemPermissionType.MENU,
					"financial-close", "/gl/bank-accounts", null, null, 884),
			new PermissionSeed("financial-close:bank-reconciliation", "银行对账", SystemPermissionType.MENU,
					"financial-close", "/gl/bank-reconciliation", null, null, 885),
			new PermissionSeed("financial-close:tax-profile", "税务基础设置", SystemPermissionType.MENU,
					"financial-close", "/gl/tax-settings", null, null, 886),
			new PermissionSeed("financial-close:tax-summary", "税务期间汇总", SystemPermissionType.MENU,
					"financial-close", "/gl/tax-summary", null, null, 887),
			new PermissionSeed("financial-close:tax-payment", "税款缴纳记录", SystemPermissionType.MENU,
					"financial-close", "/gl/tax-payments", null, null, 888),
			new PermissionSeed("financial-close:period:view", "查看财务结账期间", SystemPermissionType.ACTION,
					"financial-close:period", "/gl/financial-close", "GET",
					"/api/admin/financial-closes/**", 889),
			new PermissionSeed("financial-close:period:check", "执行财务结账检查", SystemPermissionType.ACTION,
					"financial-close:period", "/gl/financial-close", "POST",
					"/api/admin/financial-closes/periods/{id}/checks", 890),
			new PermissionSeed("financial-close:period:close", "关闭财务期间", SystemPermissionType.ACTION,
					"financial-close:period", "/gl/financial-close", "POST",
					"/api/admin/financial-closes/check-runs/{id}/close", 891),
			new PermissionSeed("financial-close:period:reopen", "申请与审批财务反结账",
					SystemPermissionType.ACTION, "financial-close:period", "/gl/financial-close", "POST",
					"/api/admin/financial-closes/close-runs/{id}/reopen-requests", 892),
			new PermissionSeed("financial-close:profit-loss:view", "查看期末损益结转",
					SystemPermissionType.ACTION, "financial-close:profit-loss", "/gl/profit-loss-carryforward",
					"GET", "/api/admin/financial-closes/periods/{id}/profit-loss-transfers/**", 893),
			new PermissionSeed("financial-close:profit-loss:generate", "生成期末损益结转凭证草稿",
					SystemPermissionType.ACTION, "financial-close:profit-loss", "/gl/profit-loss-carryforward",
					"POST", "/api/admin/financial-closes/periods/{id}/profit-loss-transfers/**", 894),
			new PermissionSeed("financial-close:bank-account:view", "查看银行账户", SystemPermissionType.ACTION,
					"financial-close:bank-account", "/gl/bank-accounts", "GET",
					"/api/admin/bank-accounts/**", 895),
			new PermissionSeed("financial-close:bank-account:manage", "维护银行账户", SystemPermissionType.ACTION,
					"financial-close:bank-account", "/gl/bank-accounts", null,
					"/api/admin/bank-accounts/**", 896),
			new PermissionSeed("financial-close:bank-reconciliation:view", "查看银行对账",
					SystemPermissionType.ACTION, "financial-close:bank-reconciliation",
					"/gl/bank-statements", "GET",
					"/api/admin/bank-statements/**,/api/admin/bank-reconciliations/**",
					897),
			new PermissionSeed("financial-close:bank-reconciliation:import", "导入银行流水",
					SystemPermissionType.ACTION, "financial-close:bank-reconciliation",
					"/gl/bank-statements", "POST",
					"/api/admin/bank-statements/**,/api/admin/bank-statement-lines/**", 898),
			new PermissionSeed("financial-close:bank-reconciliation:match", "执行银行对账匹配",
					SystemPermissionType.ACTION, "financial-close:bank-reconciliation",
					"/gl/bank-reconciliation", "POST", "/api/admin/bank-reconciliations/**",
					899),
			new PermissionSeed("financial-close:bank-reconciliation:confirm", "确认银行对账",
					SystemPermissionType.ACTION, "financial-close:bank-reconciliation",
					"/gl/bank-reconciliation", "POST",
					"/api/admin/bank-reconciliations/{id}/confirm", 900),
			new PermissionSeed("financial-close:bank-reconciliation:reopen", "重开银行对账",
					SystemPermissionType.ACTION, "financial-close:bank-reconciliation",
					"/gl/bank-reconciliation", "POST",
					"/api/admin/bank-reconciliations/{id}/reopen", 901),
			new PermissionSeed("financial-close:tax-profile:view", "查看税务基础设置",
					SystemPermissionType.ACTION, "financial-close:tax-profile", "/gl/tax-settings",
					"GET", "/api/admin/tax-profiles/**", 902),
			new PermissionSeed("financial-close:tax-profile:manage", "维护税务基础设置",
					SystemPermissionType.ACTION, "financial-close:tax-profile", "/gl/tax-settings",
					null, "/api/admin/tax-profiles/**", 903),
			new PermissionSeed("financial-close:tax-summary:view", "查看税务汇总",
					SystemPermissionType.ACTION, "financial-close:tax-summary", "/gl/tax-summary",
					"GET", "/api/admin/tax-summaries/**", 904),
			new PermissionSeed("financial-close:tax-summary:calculate", "计算税务汇总",
					SystemPermissionType.ACTION, "financial-close:tax-summary", "/gl/tax-summary",
					"POST", "/api/admin/tax-summaries/**", 905),
			new PermissionSeed("financial-close:tax-summary:confirm", "确认税务汇总",
					SystemPermissionType.ACTION, "financial-close:tax-summary", "/gl/tax-summary",
					"POST", "/api/admin/tax-summaries/{id}/confirm", 906),
			new PermissionSeed("financial-close:tax-summary:generate-voucher", "生成税务凭证草稿",
					SystemPermissionType.ACTION, "financial-close:tax-summary", "/gl/tax-summary",
					"POST", "/api/admin/tax-summaries/{id}/voucher-drafts", 907),
			new PermissionSeed("financial-close:tax-payment:view", "查看税款缴纳记录",
					SystemPermissionType.ACTION, "financial-close:tax-payment", "/gl/tax-payments",
					"GET", "/api/admin/tax-payments/**", 908),
			new PermissionSeed("financial-close:tax-payment:manage", "维护税款缴纳记录",
					SystemPermissionType.ACTION, "financial-close:tax-payment", "/gl/tax-payments",
					null, "/api/admin/tax-payments/**", 909),
			new PermissionSeed("financial-close:amount:view", "查看财务结账金额",
					SystemPermissionType.ACTION, "financial-close", "/gl/financial-close", null, null, 910),
			new PermissionSeed("financial-close:source:view", "查看财务结账来源",
					SystemPermissionType.ACTION, "financial-close", "/gl/financial-close", null, null, 911),
			new PermissionSeed("financial-close:bank-sensitive:view", "查看银行敏感字段",
					SystemPermissionType.ACTION, "financial-close:bank-account", "/gl/bank-accounts",
					null, null, 912),
			new PermissionSeed("platform", "单据平台", SystemPermissionType.MENU, null, "/platform/tasks", null,
					null, 900),
			new PermissionSeed("platform:approval", "固定审批", SystemPermissionType.MENU, "platform",
					"/platform/approvals", null, null, 910),
			new PermissionSeed("platform:approval:view", "查看审批", SystemPermissionType.ACTION,
					"platform:approval", "/platform/approvals", "GET", "/api/admin/approvals/**", 911),
			new PermissionSeed("platform:approval:cancel", "取消审批", SystemPermissionType.ACTION,
					"platform:approval", "/platform/approvals", "POST", "/api/admin/approvals/{id}/cancel", 912),
			new PermissionSeed("platform:todo:view", "查看待办", SystemPermissionType.ACTION,
					"platform:approval", "/platform/tasks", "GET", "/api/admin/approval-tasks/**", 913),
			new PermissionSeed("platform:message:view", "查看消息", SystemPermissionType.ACTION, "platform",
					"/platform/messages", "GET", "/api/admin/messages/**", 920),
			new PermissionSeed("platform:message:read", "标记消息已读", SystemPermissionType.ACTION, "platform",
					"/platform/messages", "PUT", "/api/admin/messages/**", 921),
			new PermissionSeed("platform:attachment:view", "查看附件", SystemPermissionType.ACTION, "platform",
					"/platform/attachments", "GET", "/api/admin/attachments/**", 930),
			new PermissionSeed("platform:attachment:upload", "上传附件", SystemPermissionType.ACTION, "platform",
					"/platform/attachments", "POST", "/api/admin/attachments", 931),
			new PermissionSeed("platform:attachment:download", "下载附件", SystemPermissionType.ACTION, "platform",
					"/platform/attachments", "GET", "/api/admin/attachments/{id}/download", 932),
			new PermissionSeed("platform:attachment:delete", "删除附件", SystemPermissionType.ACTION, "platform",
					"/platform/attachments", "PUT", "/api/admin/attachments/{id}/delete", 933),
			new PermissionSeed("platform:document-task:view", "查看文件任务", SystemPermissionType.ACTION,
					"platform", "/platform/document-tasks", "GET", "/api/admin/document-tasks/**", 940),
			new PermissionSeed("platform:document-task:create", "创建文件任务", SystemPermissionType.ACTION,
					"platform", "/platform/document-tasks", "POST", "/api/admin/export-tasks", 940),
			new PermissionSeed("platform:document-task:view-all", "查看全部文件任务", SystemPermissionType.ACTION,
					"platform", "/platform/document-tasks", null, null, 941),
			new PermissionSeed("platform:document-task:cancel", "取消文件任务", SystemPermissionType.ACTION,
					"platform", "/platform/document-tasks", "POST", "/api/admin/document-tasks/{id}/cancel", 942),
			new PermissionSeed("platform:document-task:download", "下载文件任务结果", SystemPermissionType.ACTION,
					"platform", "/platform/document-tasks", "GET", "/api/admin/document-tasks/{id}/download",
					943),
			new PermissionSeed("platform:print:generate", "生成固定打印单", SystemPermissionType.ACTION,
					"platform", "/platform/prints", null, "/api/admin/print-**", 950));

	private final SystemUserRepository userRepository;

	private final SystemRoleRepository roleRepository;

	private final SystemPermissionRepository permissionRepository;

	private final SystemUserRoleRepository userRoleRepository;

	private final SystemRolePermissionRepository rolePermissionRepository;

	private final PasswordEncoder passwordEncoder;

	private final String initialAdminPassword;

	public AccountPermissionInitializer(SystemUserRepository userRepository, SystemRoleRepository roleRepository,
			SystemPermissionRepository permissionRepository, SystemUserRoleRepository userRoleRepository,
			SystemRolePermissionRepository rolePermissionRepository, PasswordEncoder passwordEncoder,
			@Value("${qherp.account-permission.initial-admin-password:Qherp@2026!}") String initialAdminPassword) {
		this.userRepository = userRepository;
		this.roleRepository = roleRepository;
		this.permissionRepository = permissionRepository;
		this.userRoleRepository = userRoleRepository;
		this.rolePermissionRepository = rolePermissionRepository;
		this.passwordEncoder = passwordEncoder;
		this.initialAdminPassword = initialAdminPassword;
	}

	@Override
	@Transactional
	public void run(ApplicationArguments args) {
		initialize();
	}

	@Transactional
	public void initialize() {
		SystemUser admin = this.userRepository.findByUsername(ADMIN_USERNAME)
			.orElseGet(() -> this.userRepository.save(new SystemUser(ADMIN_USERNAME,
					this.passwordEncoder.encode(this.initialAdminPassword), "超级管理员", SystemUserStatus.ENABLED,
					SYSTEM_OPERATOR)));

		SystemRole systemAdmin = this.roleRepository.findByCode(SYSTEM_ADMIN_ROLE_CODE)
			.orElseGet(() -> this.roleRepository
				.save(new SystemRole(SYSTEM_ADMIN_ROLE_CODE, "系统管理员", SystemRoleStatus.ENABLED, 0, SYSTEM_OPERATOR)));

		Map<String, SystemPermission> permissionsByCode = new LinkedHashMap<>();
		for (PermissionSeed permission : PERMISSION_SEEDS) {
			Long parentId = permission.parentCode() == null ? null : permissionsByCode.get(permission.parentCode()).getId();
			SystemPermission savedPermission = this.permissionRepository.findByCode(permission.code())
				.orElseGet(() -> this.permissionRepository.save(new SystemPermission(permission.code(), permission.name(),
						permission.type(), parentId, permission.routePath(), permission.apiMethod(), permission.apiPath(),
						permission.sortOrder(), SYSTEM_OPERATOR)));
			permissionsByCode.put(permission.code(), savedPermission);
		}

		if (!this.userRoleRepository.existsByUserIdAndRoleId(admin.getId(), systemAdmin.getId())) {
			this.userRoleRepository.save(new SystemUserRole(admin.getId(), systemAdmin.getId(), SYSTEM_OPERATOR));
		}

		for (SystemPermission permission : permissionsByCode.values()) {
			if (!this.rolePermissionRepository.existsByRoleIdAndPermissionId(systemAdmin.getId(), permission.getId())) {
				this.rolePermissionRepository
					.save(new SystemRolePermission(systemAdmin.getId(), permission.getId(), SYSTEM_OPERATOR));
			}
		}
	}

	private record PermissionSeed(String code, String name, SystemPermissionType type, String parentCode,
			String routePath, String apiMethod, String apiPath, int sortOrder) {
	}

}
