spring.application.name=qherp-api
spring.jpa.open-in-view=false
spring.datasource.url=${QHERP_DATASOURCE_URL:jdbc:postgresql://localhost:15432/qherp}
spring.datasource.username=${QHERP_DATASOURCE_USERNAME:qherp}
spring.datasource.password=${QHERP_DATASOURCE_PASSWORD:qherp_dev_password}
