create table sys_user (
	id bigint generated by default as identity primary key,
	username varchar(64) not null,
	password_hash varchar(255) not null,
	display_name varchar(100) not null,
	status varchar(32) not null,
	last_login_at timestamptz,
	password_changed_at timestamptz,
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_sys_user_username unique (username)
);

create table sys_role (
	id bigint generated by default as identity primary key,
	code varchar(64) not null,
	name varchar(100) not null,
	status varchar(32) not null,
	sort_order integer not null default 0,
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_sys_role_code unique (code)
);

create table sys_permission (
	id bigint generated by default as identity primary key,
	code varchar(128) not null,
	name varchar(100) not null,
	type varchar(32) not null,
	parent_id bigint,
	route_path varchar(255),
	api_method varchar(16),
	api_path varchar(255),
	sort_order integer not null default 0,
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_sys_permission_code unique (code),
	constraint fk_sys_permission_parent foreign key (parent_id) references sys_permission (id)
);

create table sys_user_role (
	id bigint generated by default as identity primary key,
	user_id bigint not null,
	role_id bigint not null,
	created_by varchar(64) not null,
	created_at timestamptz not null,
	constraint uk_sys_user_role_user_role unique (user_id, role_id),
	constraint fk_sys_user_role_user foreign key (user_id) references sys_user (id),
	constraint fk_sys_user_role_role foreign key (role_id) references sys_role (id)
);

create table sys_role_permission (
	id bigint generated by default as identity primary key,
	role_id bigint not null,
	permission_id bigint not null,
	created_by varchar(64) not null,
	created_at timestamptz not null,
	constraint uk_sys_role_permission_role_permission unique (role_id, permission_id),
	constraint fk_sys_role_permission_role foreign key (role_id) references sys_role (id),
	constraint fk_sys_role_permission_permission foreign key (permission_id) references sys_permission (id)
);
