create table mst_unit (
	id bigint generated by default as identity primary key,
	code varchar(64) not null,
	name varchar(100) not null,
	precision_scale integer not null,
	status varchar(32) not null,
	sort_order integer not null,
	remark varchar(255),
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_mst_unit_code unique (code)
);

create table mst_warehouse (
	id bigint generated by default as identity primary key,
	code varchar(64) not null,
	name varchar(100) not null,
	warehouse_type varchar(32),
	manager_name varchar(100),
	address varchar(255),
	status varchar(32) not null,
	remark varchar(255),
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_mst_warehouse_code unique (code)
);

create table mst_supplier (
	id bigint generated by default as identity primary key,
	code varchar(64) not null,
	name varchar(100) not null,
	contact_name varchar(100),
	contact_phone varchar(32),
	status varchar(32) not null,
	remark varchar(255),
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_mst_supplier_code unique (code)
);

create table mst_customer (
	id bigint generated by default as identity primary key,
	code varchar(64) not null,
	name varchar(100) not null,
	contact_name varchar(100),
	contact_phone varchar(32),
	status varchar(32) not null,
	remark varchar(255),
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_mst_customer_code unique (code)
);

create table mst_material_category (
	id bigint generated by default as identity primary key,
	code varchar(64) not null,
	name varchar(100) not null,
	parent_id bigint,
	status varchar(32) not null,
	sort_order integer not null,
	remark varchar(255),
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_mst_material_category_code unique (code),
	constraint fk_mst_material_category_parent foreign key (parent_id) references mst_material_category (id)
);

create table mst_material (
	id bigint generated by default as identity primary key,
	code varchar(64) not null,
	name varchar(100) not null,
	specification varchar(255),
	material_type varchar(32) not null,
	source_type varchar(32) not null,
	category_id bigint not null,
	unit_id bigint not null,
	status varchar(32) not null,
	remark varchar(255),
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_mst_material_code unique (code),
	constraint fk_mst_material_category foreign key (category_id) references mst_material_category (id),
	constraint fk_mst_material_unit foreign key (unit_id) references mst_unit (id)
);

create index idx_mst_material_category_parent on mst_material_category (parent_id);
create index idx_mst_material_category_status on mst_material_category (status);
create index idx_mst_material_category_unit on mst_material (category_id, unit_id);
create index idx_mst_material_status on mst_material (status);
