create table sys_knowledge_category (
	id bigint generated by default as identity primary key,
	code varchar(64) not null,
	name varchar(100) not null,
	parent_id bigint,
	sort_order integer not null default 0,
	status varchar(32) not null,
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_sys_knowledge_category_code unique (code),
	constraint ck_sys_knowledge_category_status check (status in ('ENABLED', 'DISABLED')),
	constraint fk_sys_knowledge_category_parent foreign key (parent_id) references sys_knowledge_category (id)
);

create table sys_knowledge_article (
	id bigint generated by default as identity primary key,
	slug varchar(128) not null,
	title varchar(200) not null,
	summary varchar(500) not null,
	category_id bigint not null,
	knowledge_type varchar(32) not null,
	content text not null,
	keywords text,
	route_paths text,
	page_names text,
	permission_note text,
	sort_order integer not null default 0,
	status varchar(32) not null,
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_sys_knowledge_article_slug unique (slug),
	constraint ck_sys_knowledge_article_status check (status in ('ENABLED', 'DISABLED')),
	constraint ck_sys_knowledge_article_type check (
		knowledge_type in ('PAGE', 'PROCESS', 'FIELD', 'STATUS', 'ERROR', 'PERMISSION', 'IMPORT_EXPORT', 'CONCEPT')
	),
	constraint fk_sys_knowledge_article_category foreign key (category_id) references sys_knowledge_category (id)
);

create table sys_knowledge_article_relation (
	article_id bigint not null,
	related_article_id bigint not null,
	created_at timestamptz not null default now(),
	constraint pk_sys_knowledge_article_relation primary key (article_id, related_article_id),
	constraint ck_sys_knowledge_article_relation_self check (article_id <> related_article_id),
	constraint fk_sys_knowledge_article_relation_article foreign key (article_id)
		references sys_knowledge_article (id) on delete cascade,
	constraint fk_sys_knowledge_article_relation_related foreign key (related_article_id)
		references sys_knowledge_article (id) on delete cascade
);

create index idx_sys_knowledge_category_parent_sort on sys_knowledge_category (parent_id, sort_order, id);
create index idx_sys_knowledge_category_status_sort on sys_knowledge_category (status, sort_order, id);
create index idx_sys_knowledge_article_status_sort on sys_knowledge_article (status, sort_order, updated_at, id);
create index idx_sys_knowledge_article_category_status on sys_knowledge_article (category_id, status);
create index idx_sys_knowledge_article_type_status on sys_knowledge_article (knowledge_type, status);
create index idx_sys_knowledge_article_updated_at on sys_knowledge_article (updated_at);
create index idx_sys_knowledge_article_relation_related on sys_knowledge_article_relation (related_article_id);

insert into sys_permission (code, name, type, parent_id, route_path, api_method, api_path, sort_order,
	created_by, created_at, updated_by, updated_at)
select 'system:knowledge', '系统知识库管理', 'MENU', parent.id, '/system/knowledge',
       null, null, 90, 'system', now(), 'system', now()
from sys_permission parent
where parent.code = 'system'
on conflict (code) do update
set name = excluded.name,
    parent_id = excluded.parent_id,
    route_path = excluded.route_path,
    sort_order = excluded.sort_order,
    updated_by = 'system',
    updated_at = now();

insert into sys_permission (code, name, type, parent_id, route_path, api_method, api_path, sort_order,
	created_by, created_at, updated_by, updated_at)
select 'system:knowledge:manage', '维护系统知识库', 'ACTION', parent.id, '/system/knowledge',
       null, '/api/admin/system/knowledge/**', 91, 'system', now(), 'system', now()
from sys_permission parent
where parent.code = 'system:knowledge'
on conflict (code) do update
set name = excluded.name,
    parent_id = excluded.parent_id,
    route_path = excluded.route_path,
    api_method = excluded.api_method,
    api_path = excluded.api_path,
    sort_order = excluded.sort_order,
    updated_by = 'system',
    updated_at = now();

insert into sys_role_permission (role_id, permission_id, created_by, created_at)
select r.id, p.id, 'system', now()
from sys_role r
join sys_permission p on p.code in ('system:knowledge', 'system:knowledge:manage')
where r.code = 'SYSTEM_ADMIN'
and not exists (
	select 1
	from sys_role_permission rp
	where rp.role_id = r.id
	and rp.permission_id = p.id
);
