create table mfg_bom (
	id bigint generated by default as identity primary key,
	bom_code varchar(64) not null,
	parent_material_id bigint not null,
	version_code varchar(32) not null,
	name varchar(128) not null,
	base_quantity numeric(18, 6) not null,
	base_unit_id bigint not null,
	status varchar(32) not null,
	effective_from date,
	effective_to date,
	remark varchar(500),
	enabled_by varchar(64),
	enabled_at timestamptz,
	created_by varchar(64) not null,
	created_at timestamptz not null,
	updated_by varchar(64) not null,
	updated_at timestamptz not null,
	version bigint not null default 0,
	constraint uk_mfg_bom_code unique (bom_code),
	constraint uk_mfg_bom_parent_version unique (parent_material_id, version_code),
	constraint fk_mfg_bom_parent_material foreign key (parent_material_id) references mst_material (id),
	constraint fk_mfg_bom_base_unit foreign key (base_unit_id) references mst_unit (id),
	constraint ck_mfg_bom_base_quantity_positive check (base_quantity > 0),
	constraint ck_mfg_bom_status check (status in ('DRAFT', 'ENABLED', 'DISABLED'))
);

create unique index uk_mfg_bom_enabled_parent
	on mfg_bom (parent_material_id)
	where status = 'ENABLED';

create table mfg_bom_item (
	id bigint generated by default as identity primary key,
	bom_id bigint not null,
	line_no integer not null,
	child_material_id bigint not null,
	unit_id bigint not null,
	quantity numeric(18, 6) not null,
	loss_rate numeric(9, 6) not null default 0,
	remark varchar(500),
	created_at timestamptz not null,
	updated_at timestamptz not null,
	constraint fk_mfg_bom_item_bom foreign key (bom_id) references mfg_bom (id) on delete cascade,
	constraint fk_mfg_bom_item_child_material foreign key (child_material_id) references mst_material (id),
	constraint fk_mfg_bom_item_unit foreign key (unit_id) references mst_unit (id),
	constraint uk_mfg_bom_item_line unique (bom_id, line_no),
	constraint uk_mfg_bom_item_material unique (bom_id, child_material_id),
	constraint ck_mfg_bom_item_quantity_positive check (quantity > 0),
	constraint ck_mfg_bom_item_loss_rate_range check (loss_rate >= 0 and loss_rate < 1)
);

create index idx_mfg_bom_parent_status on mfg_bom (parent_material_id, status);
create index idx_mfg_bom_item_child_material on mfg_bom_item (child_material_id);
