package com.qherp.api.common;

import org.springframework.http.HttpStatus;

public enum ApiErrorCode {

	OK("OK", "成功", HttpStatus.OK),

	VALIDATION_ERROR("VALIDATION_ERROR", "参数校验失败", HttpStatus.BAD_REQUEST),

	AUTH_UNAUTHORIZED("AUTH_UNAUTHORIZED", "未认证或登录已过期", HttpStatus.UNAUTHORIZED),

	AUTH_FORBIDDEN("AUTH_FORBIDDEN", "无访问权限", HttpStatus.FORBIDDEN),

	AUTH_ACCOUNT_DISABLED("AUTH_ACCOUNT_DISABLED", "账号已停用", HttpStatus.FORBIDDEN),

	AUTH_USERNAME_EXISTS("AUTH_USERNAME_EXISTS", "用户名已存在", HttpStatus.CONFLICT),

	AUTH_ROLE_CODE_EXISTS("AUTH_ROLE_CODE_EXISTS", "角色编码已存在", HttpStatus.CONFLICT),

	AUTH_INVALID_PASSWORD_RULE("AUTH_INVALID_PASSWORD_RULE", "密码不符合规则", HttpStatus.BAD_REQUEST),

	AUTH_ROLE_DISABLED("AUTH_ROLE_DISABLED", "角色已停用", HttpStatus.FORBIDDEN),

	AUTH_PERMISSION_NOT_FOUND("AUTH_PERMISSION_NOT_FOUND", "权限点不存在", HttpStatus.NOT_FOUND),

	AUTH_INIT_ADMIN_FAILED("AUTH_INIT_ADMIN_FAILED", "初始管理员初始化失败", HttpStatus.INTERNAL_SERVER_ERROR),

	MASTER_DATA_CODE_EXISTS(HttpStatus.CONFLICT, "主数据编码已存在"),

	MASTER_DATA_NOT_FOUND(HttpStatus.NOT_FOUND, "主数据不存在"),

	MASTER_DATA_INVALID_STATUS(HttpStatus.BAD_REQUEST, "主数据状态不正确"),

	MATERIAL_DISABLED(HttpStatus.BAD_REQUEST, "物料已停用"),

	MASTER_DATA_REFERENCE_INVALID(HttpStatus.BAD_REQUEST, "主数据引用不正确"),

	MASTER_DATA_CATEGORY_IN_USE(HttpStatus.CONFLICT, "物料分类已被启用数据引用"),

	MASTER_DATA_CATEGORY_PARENT_INVALID(HttpStatus.BAD_REQUEST, "物料分类父级不正确"),

	MASTER_DATA_UNIT_IN_USE(HttpStatus.CONFLICT, "计量单位已被启用物料引用"),

	BOM_NOT_FOUND(HttpStatus.NOT_FOUND, "BOM 不存在"),

	BOM_NOT_EFFECTIVE(HttpStatus.BAD_REQUEST, "BOM 在需求日期未生效"),

	BOM_CODE_EXISTS(HttpStatus.CONFLICT, "BOM 编码已存在"),

	BOM_VERSION_EXISTS(HttpStatus.CONFLICT, "同一父项物料的 BOM 版本已存在"),

	BOM_ENABLED_VERSION_EXISTS(HttpStatus.CONFLICT, "同一父项物料已存在启用 BOM"),

	BOM_STATUS_NOT_EDITABLE(HttpStatus.CONFLICT, "当前 BOM 状态不可编辑"),

	VERSION_CONFLICT(HttpStatus.CONFLICT, "数据版本已变化，请刷新后重试"),

	UNIT_CONVERSION_NOT_FOUND(HttpStatus.NOT_FOUND, "单位换算关系不存在"),

	UNIT_CONVERSION_RATE_INVALID(HttpStatus.BAD_REQUEST, "单位换算比例、精度或舍入方式不正确"),

	UNIT_CONVERSION_DATE_RANGE_INVALID(HttpStatus.BAD_REQUEST, "单位换算有效期不正确"),

	UNIT_CONVERSION_EFFECTIVE_OVERLAP(HttpStatus.CONFLICT, "同一物料同一业务单位存在重叠启用换算关系"),

	UNIT_CONVERSION_REQUIRED(HttpStatus.CONFLICT, "缺少可用单位换算关系"),

	MATERIAL_BASE_UNIT_IMMUTABLE(HttpStatus.CONFLICT, "已有业务事实的物料基本单位被普通编辑改变。"),

	MATERIAL_COST_ATTRIBUTE_INCOMPLETE(HttpStatus.BAD_REQUEST, "物料成本属性不完整"),

	CODING_RULE_NOT_FOUND(HttpStatus.NOT_FOUND, "编码规则不存在"),

	CODING_RULE_OBJECT_TYPE_INVALID(HttpStatus.BAD_REQUEST, "编码对象类型不正确"),

	CODING_RULE_DISABLED(HttpStatus.CONFLICT, "编码规则未启用或不存在"),

	CODING_RULE_DUPLICATE_ENABLED(HttpStatus.CONFLICT, "同一对象类型存在多个启用编码规则"),

	CODING_RULE_GENERATE_CONFLICT(HttpStatus.CONFLICT, "编码生成冲突"),

	SETTLEMENT_TAX_FIELD_INVALID(HttpStatus.BAD_REQUEST, "结算税务字段不正确"),

	SETTLEMENT_TAX_SENSITIVE_FORBIDDEN(HttpStatus.FORBIDDEN, "无权访问或维护敏感结算税务字段"),

	SETTLEMENT_TAX_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "结算税务资料并发更新冲突"),

	BOM_EFFECTIVE_DATE_RANGE_INVALID(HttpStatus.BAD_REQUEST, "BOM 有效期不正确"),

	BOM_EFFECTIVE_DATE_OVERLAP(HttpStatus.CONFLICT, "同一父项物料存在重叠已发布 BOM 有效期"),

	BOM_LEGACY_UNIT_CONVERSION_REQUIRED(HttpStatus.CONFLICT, "历史 BOM 行缺少单位换算快照，不能发布"),

	BOM_ENGINEERING_CHANGE_NOT_FOUND(HttpStatus.NOT_FOUND, "工程变更不存在"),

	BOM_ENGINEERING_CHANGE_STATUS_INVALID(HttpStatus.CONFLICT, "工程变更状态不允许当前操作"),

	BOM_ENGINEERING_CHANGE_TARGET_INVALID(HttpStatus.BAD_REQUEST, "工程变更来源或目标 BOM 不正确"),

	BOM_ENGINEERING_CHANGE_EFFECTIVE_INVALID(HttpStatus.BAD_REQUEST, "工程变更生效日期不正确"),

	BOM_ENGINEERING_CHANGE_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "工程变更并发更新冲突"),

	APPROVAL_REQUIRED(HttpStatus.CONFLICT, "当前业务动作必须通过审批执行"),

	APPROVAL_DEFINITION_NOT_FOUND(HttpStatus.NOT_FOUND, "审批定义不存在"),

	APPROVAL_OBJECT_NOT_SUPPORTED(HttpStatus.BAD_REQUEST, "审批对象不支持"),

	APPROVAL_DUPLICATE_ACTIVE(HttpStatus.CONFLICT, "当前对象已有未完成审批"),

	APPROVAL_IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, "审批幂等键冲突"),

	APPROVAL_STATUS_INVALID(HttpStatus.CONFLICT, "审批状态不允许当前操作"),

	APPROVAL_SELF_ACTION_FORBIDDEN(HttpStatus.FORBIDDEN, "提交人不能审批自己的申请"),

	APPROVAL_BUSINESS_OBJECT_CHANGED(HttpStatus.CONFLICT, "业务对象已变化，请撤回后重新提交"),

	APPROVAL_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "审批并发更新冲突"),

	ATTACHMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "附件不存在"),

	ATTACHMENT_ACCESS_FORBIDDEN(HttpStatus.FORBIDDEN, "无权访问附件"),

	ATTACHMENT_FILE_TYPE_INVALID(HttpStatus.BAD_REQUEST, "附件文件类型不允许"),

	ATTACHMENT_FILE_SIZE_EXCEEDED(HttpStatus.BAD_REQUEST, "附件文件大小超过限制"),

	FILE_STORAGE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "文件存储不可用"),

	DOCUMENT_TASK_NOT_FOUND(HttpStatus.NOT_FOUND, "文档任务不存在"),

	DOCUMENT_TASK_STATUS_INVALID(HttpStatus.CONFLICT, "文档任务状态不允许当前操作"),

	DOCUMENT_TASK_IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, "文档任务幂等键冲突"),

	DOCUMENT_TASK_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "文档任务并发更新冲突"),

	IMPORT_FILE_INVALID(HttpStatus.BAD_REQUEST, "导入文件不合法"),

	IMPORT_VALIDATION_FAILED(HttpStatus.CONFLICT, "导入校验失败"),

	IMPORT_APPLY_FAILED(HttpStatus.CONFLICT, "导入提交失败"),

	DOCUMENT_RESULT_EXPIRED(HttpStatus.GONE, "文档结果已过期"),

	PRINT_TEMPLATE_NOT_SUPPORTED(HttpStatus.BAD_REQUEST, "打印模板不支持"),

	DATA_REPAIR_NOT_FOUND(HttpStatus.NOT_FOUND, "数据修复申请不存在"),

	DATA_REPAIR_STATUS_INVALID(HttpStatus.CONFLICT, "数据修复状态不允许当前操作"),

	DATA_REPAIR_ADAPTER_NOT_SUPPORTED(HttpStatus.BAD_REQUEST, "数据修复适配器不支持"),

	DATA_REPAIR_FIELD_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "数据修复字段不在白名单内"),

	DATA_REPAIR_SELF_APPROVAL_FORBIDDEN(HttpStatus.FORBIDDEN, "申请人不能审批自己的数据修复"),

	DATA_REPAIR_SELF_VERIFY_FORBIDDEN(HttpStatus.FORBIDDEN, "执行人不能验证自己的数据修复"),

	DATA_REPAIR_OBJECT_CHANGED(HttpStatus.CONFLICT, "数据修复对象已变化，请重新申请"),

	DATA_REPAIR_EXECUTION_FAILED(HttpStatus.CONFLICT, "数据修复执行失败"),

	DATA_REPAIR_VERIFICATION_FAILED(HttpStatus.CONFLICT, "数据修复验证失败"),

	HISTORY_IMPORT_ADAPTER_NOT_SUPPORTED(HttpStatus.BAD_REQUEST, "历史导入适配器不支持"),

	HISTORY_IMPORT_TEMPLATE_VERSION_MISMATCH(HttpStatus.CONFLICT, "历史导入模板版本不匹配"),

	HISTORY_IMPORT_ALREADY_EXISTS(HttpStatus.CONFLICT, "历史导入数据已存在"),

	BATCH_TOOL_NOT_SUPPORTED(HttpStatus.BAD_REQUEST, "固定批量工具不支持"),

	BATCH_OPERATION_STATUS_INVALID(HttpStatus.CONFLICT, "批量操作状态不允许当前动作"),

	BATCH_OPERATION_PRECHECK_FAILED(HttpStatus.CONFLICT, "批量操作预检失败"),

	BATCH_OPERATION_OBJECT_CHANGED(HttpStatus.CONFLICT, "批量操作对象已变化，请重新预检"),

	DELIVERY_ASSET_NOT_AVAILABLE(HttpStatus.NOT_FOUND, "交付资料不可用"),

	MATERIAL_SUBSTITUTE_NOT_FOUND(HttpStatus.NOT_FOUND, "替代料关系不存在"),

	MATERIAL_SUBSTITUTE_SELF_REFERENCE(HttpStatus.BAD_REQUEST, "主物料和替代物料不能相同"),

	MATERIAL_SUBSTITUTE_PRIORITY_CONFLICT(HttpStatus.CONFLICT, "替代料优先级冲突"),

	MATERIAL_SUBSTITUTE_EFFECTIVE_OVERLAP(HttpStatus.CONFLICT, "替代料有效期冲突"),

	MATERIAL_SUBSTITUTE_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "替代料并发更新冲突"),

	PRODUCTION_UNIT_CONVERSION_REQUIRED(HttpStatus.CONFLICT, "历史工单快照缺少单位换算快照，不能继续过账"),

	BOM_PARENT_MATERIAL_INVALID(HttpStatus.BAD_REQUEST, "BOM 父项物料不正确"),

	BOM_CHILD_MATERIAL_INVALID(HttpStatus.BAD_REQUEST, "BOM 子项物料不正确"),

	BOM_UNIT_INVALID(HttpStatus.BAD_REQUEST, "BOM 单位不正确"),

	BOM_EMPTY_ITEMS(HttpStatus.BAD_REQUEST, "BOM 明细不能为空"),

	BOM_QUANTITY_INVALID(HttpStatus.BAD_REQUEST, "BOM 数量或损耗率不正确"),

	BOM_DUPLICATE_ITEM(HttpStatus.CONFLICT, "BOM 明细子项重复"),

	BOM_SELF_REFERENCE(HttpStatus.BAD_REQUEST, "BOM 父项物料不能作为子项"),

	BOM_CYCLE_DETECTED(HttpStatus.CONFLICT, "BOM 存在循环引用"),

	INVENTORY_DOCUMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "库存单据不存在"),

	INVENTORY_DOCUMENT_TYPE_INVALID(HttpStatus.BAD_REQUEST, "库存单据类型不正确"),

	INVENTORY_DOCUMENT_STATUS_INVALID(HttpStatus.CONFLICT, "库存单据状态不允许当前操作"),

	INVENTORY_DOCUMENT_POSTED_IMMUTABLE(HttpStatus.CONFLICT, "已过账单据不可编辑"),

	INVENTORY_DOCUMENT_EMPTY_LINES(HttpStatus.BAD_REQUEST, "库存单据明细不能为空"),

	INVENTORY_DOCUMENT_DUPLICATE_LINE(HttpStatus.CONFLICT, "库存单据明细重复"),

	INVENTORY_QUANTITY_INVALID(HttpStatus.BAD_REQUEST, "库存数量不正确"),

	INVENTORY_STOCK_NOT_ENOUGH(HttpStatus.CONFLICT, "库存不足，调减后库存不能小于 0"),

	INVENTORY_WAREHOUSE_INVALID(HttpStatus.BAD_REQUEST, "仓库不存在或已停用"),

	INVENTORY_MATERIAL_INVALID(HttpStatus.BAD_REQUEST, "物料不存在或已停用"),

	INVENTORY_UNIT_INVALID(HttpStatus.BAD_REQUEST, "单位不存在、已停用或不是物料基本单位"),

	INVENTORY_OPENING_EXISTS(HttpStatus.CONFLICT, "同一仓库物料已存在已过账期初"),

	INVENTORY_DUPLICATE_POST(HttpStatus.CONFLICT, "库存单据已过账或重复过账"),

	INVENTORY_MOVEMENT_SOURCE_DUPLICATED(HttpStatus.CONFLICT, "来源明细已生成库存变动"),

	INVENTORY_QUALITY_STATUS_REQUIRED(HttpStatus.BAD_REQUEST, "库存质量状态必填"),

	INVENTORY_QUALITY_STATUS_INVALID(HttpStatus.BAD_REQUEST, "库存质量状态不正确"),

	INVENTORY_NON_QUALIFIED_NOT_AVAILABLE(HttpStatus.CONFLICT, "非合格库存不可用于当前业务"),

	INVENTORY_QUALITY_STATUS_BALANCE_NOT_ENOUGH(HttpStatus.CONFLICT, "指定质量状态库存不足"),

	INVENTORY_AVAILABLE_NOT_ENOUGH(HttpStatus.CONFLICT, "库存可用量不足"),

	INVENTORY_ATP_NOT_ENOUGH(HttpStatus.CONFLICT, "库存可承诺量不足"),

	INVENTORY_RESERVATION_NOT_FOUND(HttpStatus.NOT_FOUND, "库存预留记录不存在"),

	INVENTORY_RESERVATION_SOURCE_DUPLICATED(HttpStatus.CONFLICT, "库存预留来源已存在"),

	INVENTORY_RESERVATION_STATUS_INVALID(HttpStatus.CONFLICT, "库存预留状态不允许当前操作"),

	INVENTORY_RESERVATION_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "库存预留并发更新冲突"),

	INVENTORY_RESERVED_OR_OCCUPIED_NOT_AVAILABLE(HttpStatus.CONFLICT, "库存已被预留或占用，不可用于当前业务"),

	INVENTORY_IN_TRANSIT_NOT_AVAILABLE(HttpStatus.CONFLICT, "在途库存不可用于现货出库"),

	INVENTORY_TRACKING_METHOD_IMMUTABLE(HttpStatus.CONFLICT, "已有库存、流水或活动预留的物料不允许切换追踪方式"),

	INVENTORY_BATCH_REQUIRED(HttpStatus.BAD_REQUEST, "批次物料缺少批次分配"),

	INVENTORY_SERIAL_REQUIRED(HttpStatus.BAD_REQUEST, "序列号物料缺少序列分配"),

	INVENTORY_SERIAL_DUPLICATED(HttpStatus.CONFLICT, "同一物料下序列号重复"),

	INVENTORY_TRACKING_QUANTITY_MISMATCH(HttpStatus.BAD_REQUEST, "追踪分配数量与业务行数量不一致"),

	INVENTORY_TRACKING_STOCK_NOT_ENOUGH(HttpStatus.CONFLICT, "指定批次或序列库存不足"),

	INVENTORY_TRACKING_NOT_AVAILABLE(HttpStatus.CONFLICT, "指定批次或序列不可用于当前业务"),

	INVENTORY_TRACKING_SOURCE_MISMATCH(HttpStatus.CONFLICT, "追踪来源与当前业务来源不一致"),

	INVENTORY_TRACKING_NOT_FOUND(HttpStatus.NOT_FOUND, "批次或序列号不存在"),

	INVENTORY_VALUATION_UNIT_COST_REQUIRED(HttpStatus.BAD_REQUEST, "估值入库必须提供单位成本"),

	INVENTORY_HISTORICAL_UNVALUED_COST_BLOCKED(HttpStatus.CONFLICT, "历史未知成本库存需先完成期初估值"),

	INVENTORY_PUBLIC_VALUATION_POOL_INSUFFICIENT(HttpStatus.CONFLICT, "公共估值池数量或金额不足"),

	INVENTORY_PUBLIC_POOL_INSUFFICIENT(HttpStatus.CONFLICT, "公共计价池数量或金额不足"),

	INVENTORY_PROJECT_COST_LAYER_INSUFFICIENT(HttpStatus.CONFLICT, "项目成本层数量或金额不足"),

	INVENTORY_OWNERSHIP_PROJECT_MISMATCH(HttpStatus.CONFLICT, "库存所有权与项目归属不匹配"),

	INVENTORY_COST_PERMISSION_REQUIRED(HttpStatus.FORBIDDEN, "缺少库存成本查看权限"),

	INVENTORY_STOCKTAKE_RANGE_LOCKED(HttpStatus.CONFLICT, "盘点范围已锁定"),

	INVENTORY_STOCKTAKE_UNCOUNTED_LINE_EXISTS(HttpStatus.CONFLICT, "存在未盘点行"),

	INVENTORY_STOCKTAKE_VARIANCE_REQUIRES_APPROVAL(HttpStatus.CONFLICT, "盘点存在盘差，需提交审批"),

	INVENTORY_STOCKTAKE_VARIANCE_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "项目盘盈原因必填"),

	INVENTORY_STOCKTAKE_EVIDENCE_REQUIRED(HttpStatus.BAD_REQUEST, "项目盘盈必须上传有效盘点证据附件"),

	QUALITY_STATUS_TRANSITION_INVALID(HttpStatus.CONFLICT, "质量状态转换路径不允许"),

	QUALITY_INSPECTION_NOT_FOUND(HttpStatus.NOT_FOUND, "质量确认记录不存在"),

	QUALITY_INSPECTION_SOURCE_INVALID(HttpStatus.CONFLICT, "质量确认来源不合法"),

	QUALITY_INSPECTION_QUANTITY_MISMATCH(HttpStatus.BAD_REQUEST, "质量确认数量不匹配"),

	QUALITY_INSPECTION_STATUS_INVALID(HttpStatus.CONFLICT, "质量确认状态不允许当前操作"),

	QUALITY_STATUS_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "质量状态操作原因必填"),

	PRODUCTION_WORK_ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "生产工单不存在"),

	PRODUCTION_WORK_ORDER_STATUS_INVALID(HttpStatus.CONFLICT, "生产工单状态不允许当前操作"),

	PRODUCTION_WORK_ORDER_HAS_POSTED_BUSINESS(HttpStatus.CONFLICT, "生产工单已有过账业务，不能取消"),

	PRODUCTION_PRODUCT_MATERIAL_INVALID(HttpStatus.BAD_REQUEST, "产品物料不存在、停用或类型不允许"),

	PRODUCTION_BOM_INVALID(HttpStatus.BAD_REQUEST, "生产 BOM 不存在、未启用或父项物料不匹配"),

	PRODUCTION_BOM_EFFECTIVE_DATE_INVALID(HttpStatus.CONFLICT, "所选 BOM 在计划开工日期不生效，请选择有效 BOM 或调整计划开工日期"),

	PRODUCTION_BOM_EMPTY_ITEMS(HttpStatus.BAD_REQUEST, "生产 BOM 明细不能为空"),

	PRODUCTION_WAREHOUSE_INVALID(HttpStatus.BAD_REQUEST, "生产仓库不存在或已停用"),

	PRODUCTION_MATERIAL_INVALID(HttpStatus.BAD_REQUEST, "生产用料物料不存在或已停用"),

	PRODUCTION_UNIT_INVALID(HttpStatus.BAD_REQUEST, "生产单位不存在或已停用"),

	PRODUCTION_QUANTITY_INVALID(HttpStatus.BAD_REQUEST, "生产数量不正确"),

	PRODUCTION_ISSUE_NOT_FOUND(HttpStatus.NOT_FOUND, "生产领料单不存在"),

	PRODUCTION_ISSUE_EMPTY_LINES(HttpStatus.BAD_REQUEST, "生产领料明细不能为空"),

	PRODUCTION_ISSUE_EXCEEDS_REQUIRED(HttpStatus.CONFLICT, "累计领料超过应领数量"),

	PRODUCTION_ISSUE_WAREHOUSE_MISMATCH(HttpStatus.CONFLICT, "生产领料仓库必须与工单领料仓库一致"),

	PRODUCTION_STOCK_NOT_ENOUGH(HttpStatus.CONFLICT, "生产领料库存不足"),

	PRODUCTION_REPORT_NOT_FOUND(HttpStatus.NOT_FOUND, "生产报工单不存在"),

	PRODUCTION_REPORT_EXCEEDS_PLAN(HttpStatus.CONFLICT, "累计报工超过计划数量"),

	PRODUCTION_RECEIPT_NOT_FOUND(HttpStatus.NOT_FOUND, "完工入库单不存在"),

	PRODUCTION_RECEIPT_EXCEEDS_REPORTED(HttpStatus.CONFLICT, "累计入库超过累计合格报工数量"),

	PRODUCTION_DOCUMENT_POSTED_IMMUTABLE(HttpStatus.CONFLICT, "已过账生产单据不可编辑"),

	PRODUCTION_DUPLICATE_POST(HttpStatus.CONFLICT, "生产单据已过账或重复过账"),

	PRODUCTION_MOVEMENT_SOURCE_DUPLICATED(HttpStatus.CONFLICT, "生产来源明细已生成库存变动"),

	PRODUCTION_ACTION_IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, "生产业务动作幂等键冲突"),

	PRODUCTION_PROJECT_REQUIRED(HttpStatus.BAD_REQUEST, "生产项目归属必填"),

	PRODUCTION_PROJECT_INVALID(HttpStatus.BAD_REQUEST, "生产项目归属不合法"),

	PRODUCTION_PROJECT_MISMATCH(HttpStatus.CONFLICT, "生产项目归属与来源不一致"),

	PRODUCTION_PLANNING_SUGGESTION_INVALID(HttpStatus.CONFLICT, "缺料建议不能转换为当前生产目标"),

	PRODUCTION_PLANNING_SUGGESTION_ALREADY_CONVERTED(HttpStatus.CONFLICT, "缺料建议已转换为生产目标"),

	PRODUCTION_OWNERSHIP_SOURCE_INVALID(HttpStatus.CONFLICT, "生产库存来源归属不合法"),

	PRODUCTION_OUTSOURCING_STATUS_INVALID(HttpStatus.CONFLICT, "外协订单状态不允许当前操作"),

	PRODUCTION_OUTSOURCING_NOT_FOUND(HttpStatus.NOT_FOUND, "外协订单不存在"),

	PRODUCTION_OUTSOURCING_ISSUE_NOT_FOUND(HttpStatus.NOT_FOUND, "外协发料不存在或无权查看"),

	PRODUCTION_OUTSOURCING_RECEIPT_NOT_FOUND(HttpStatus.NOT_FOUND, "外协收货不存在或无权查看"),

	PRODUCTION_OUTSOURCING_SUPPLIER_REQUIRED(HttpStatus.BAD_REQUEST, "外协订单供应商必填"),

	PROCUREMENT_ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "采购订单不存在"),

	PROCUREMENT_RECEIPT_NOT_FOUND(HttpStatus.NOT_FOUND, "采购入库单不存在"),

	PROCUREMENT_ORDER_STATUS_INVALID(HttpStatus.CONFLICT, "采购订单状态不允许当前操作"),

	PROCUREMENT_RECEIPT_STATUS_INVALID(HttpStatus.CONFLICT, "采购入库单状态不允许当前操作"),

	PROCUREMENT_ORDER_EMPTY_LINES(HttpStatus.BAD_REQUEST, "采购订单明细不能为空"),

	PROCUREMENT_RECEIPT_EMPTY_LINES(HttpStatus.BAD_REQUEST, "采购入库明细不能为空"),

	PROCUREMENT_SUPPLIER_INVALID(HttpStatus.BAD_REQUEST, "供应商不存在或已停用"),

	PROCUREMENT_WAREHOUSE_INVALID(HttpStatus.BAD_REQUEST, "采购入库仓库不存在或已停用"),

	PROCUREMENT_MATERIAL_INVALID(HttpStatus.BAD_REQUEST, "采购物料不存在、已停用或不可采购"),

	PROCUREMENT_UNIT_INVALID(HttpStatus.BAD_REQUEST, "采购单位不存在、已停用或不是物料基本单位"),

	PROCUREMENT_QUANTITY_INVALID(HttpStatus.BAD_REQUEST, "采购数量不正确"),

	PROCUREMENT_UNIT_PRICE_INVALID(HttpStatus.BAD_REQUEST, "采购单价不正确"),

	PROCUREMENT_ORDER_DUPLICATE_LINE(HttpStatus.CONFLICT, "采购订单明细物料重复"),

	PROCUREMENT_RECEIPT_DUPLICATE_LINE(HttpStatus.CONFLICT, "采购入库明细来源订单行重复"),

	PROCUREMENT_RECEIPT_EXCEEDS_ORDER(HttpStatus.CONFLICT, "采购入库数量超过订单未入库数量"),

	PROCUREMENT_RECEIPT_LINE_SOURCE_INVALID(HttpStatus.CONFLICT, "采购入库明细来源不正确"),

	PROCUREMENT_RECEIPT_POSTED_IMMUTABLE(HttpStatus.CONFLICT, "已过账采购入库单不可编辑"),

	PROCUREMENT_DUPLICATE_POST(HttpStatus.CONFLICT, "采购入库单已过账或重复过账"),

	PROCUREMENT_MOVEMENT_SOURCE_DUPLICATED(HttpStatus.CONFLICT, "采购来源明细已生成库存变动"),

	PROCUREMENT_REQUISITION_NOT_FOUND(HttpStatus.NOT_FOUND, "采购请购不存在"),

	PROCUREMENT_REQUISITION_STATUS_INVALID(HttpStatus.CONFLICT, "采购请购状态不允许当前操作"),

	PROCUREMENT_REQUISITION_EMPTY_LINES(HttpStatus.BAD_REQUEST, "采购请购明细不能为空"),

	PROCUREMENT_REQUISITION_PROJECT_REQUIRED(HttpStatus.BAD_REQUEST, "项目专采请购必须关联项目"),

	PROCUREMENT_REQUISITION_PROJECT_INVALID(HttpStatus.BAD_REQUEST, "项目专采请购项目不合法"),

	PROCUREMENT_PROJECT_STATUS_INVALID(HttpStatus.CONFLICT, "项目专采只允许关联已激活项目"),

	PROCUREMENT_CURRENCY_UNSUPPORTED(HttpStatus.BAD_REQUEST, "采购首版仅支持 CNY"),

	PROCUREMENT_PUBLIC_DIRECT_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "公共直采必须填写原因"),

	PROCUREMENT_PUBLIC_DIRECT_PERMISSION_REQUIRED(HttpStatus.FORBIDDEN, "缺少公共直采权限"),

	PROCUREMENT_ORDER_SOURCE_REQUIRED(HttpStatus.CONFLICT, "项目专采订单必须来源于已批准请购"),

	PROCUREMENT_ORDER_REQUISITION_REQUIRED(HttpStatus.CONFLICT, "项目专采订单必须来源于已批准请购"),

	PROCUREMENT_ORDER_PROJECT_MISMATCH(HttpStatus.CONFLICT, "采购订单项目归属与来源不一致"),

	PROCUREMENT_ORDER_APPROVAL_REQUIRED(HttpStatus.CONFLICT, "采购订单确认必须先通过例外审批"),

	PROCUREMENT_ORDER_PUBLIC_DIRECT_APPROVAL_REQUIRED(HttpStatus.CONFLICT, "公共直采订单确认必须先通过例外审批"),

	PROCUREMENT_ORDER_EXCEPTION_APPROVAL_REQUIRED(HttpStatus.CONFLICT, "采购订单例外确认必须先通过审批"),

	PROCUREMENT_ORDER_AGREEMENT_DEVIATION(HttpStatus.CONFLICT, "采购订单价格偏离有效协议价"),

	PROCUREMENT_ORDER_PROJECT_IMMUTABLE(HttpStatus.CONFLICT, "已确认采购订单所有权和项目不可改写"),

	PROCUREMENT_PRICE_SOURCE_INVALID(HttpStatus.CONFLICT, "采购价格来源不合法"),

	PROCUREMENT_SCHEDULE_INVALID(HttpStatus.BAD_REQUEST, "采购到货计划不合法"),

	PROCUREMENT_RECEIPT_EXCEEDS_SCHEDULE(HttpStatus.CONFLICT, "采购入库数量超过到货计划未入库数量"),

	PROCUREMENT_INQUIRY_NOT_FOUND(HttpStatus.NOT_FOUND, "采购询价不存在"),

	PROCUREMENT_INQUIRY_STATUS_INVALID(HttpStatus.CONFLICT, "采购询价状态不允许当前操作"),

	PROCUREMENT_QUOTE_NOT_FOUND(HttpStatus.NOT_FOUND, "供应商报价不存在"),

	PROCUREMENT_QUOTE_INVALID(HttpStatus.CONFLICT, "供应商报价不合法"),

	PROCUREMENT_PRICE_AGREEMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "采购价格协议不存在"),

	PROCUREMENT_PRICE_AGREEMENT_STATUS_INVALID(HttpStatus.CONFLICT, "采购价格协议状态不允许当前操作"),

	PROCUREMENT_PRICE_AGREEMENT_OVERLAP(HttpStatus.CONFLICT, "采购价格协议存在重叠"),

	PROCUREMENT_PRICE_AGREEMENT_APPROVAL_REQUIRED(HttpStatus.CONFLICT, "价格协议激活必须先通过审批"),

	PROCUREMENT_ACTION_IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, "采购业务动作幂等键冲突"),

	MATERIAL_REQUIREMENT_RUN_NOT_FOUND(HttpStatus.NOT_FOUND, "缺料净算运行不存在"),

	MATERIAL_REQUIREMENT_RUN_CONFLICT(HttpStatus.CONFLICT, "缺料净算幂等键冲突"),

	MATERIAL_REQUIREMENT_RUN_STALE(HttpStatus.CONFLICT, "缺料净算来源已变化，请重新计算"),

	MATERIAL_REQUIREMENT_RUN_EXPIRED(HttpStatus.CONFLICT, "缺料净算快照已过期，请重新计算"),

	MATERIAL_REQUIREMENT_SUGGESTION_NOT_FOUND(HttpStatus.NOT_FOUND, "缺料建议不存在"),

	MATERIAL_REQUIREMENT_SUGGESTION_STATE_CONFLICT(HttpStatus.CONFLICT, "缺料建议状态不允许当前操作"),

	MATERIAL_REQUIREMENT_REQUISITION_ALREADY_CONVERTED(HttpStatus.CONFLICT, "缺料建议已转为采购请购"),

	MATERIAL_REQUIREMENT_SOURCE_CHANGED(HttpStatus.CONFLICT, "缺料净算来源已变化"),

	SALES_ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "销售订单不存在"),

	SALES_SHIPMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "销售出库单不存在"),

	SALES_ORDER_STATUS_INVALID(HttpStatus.CONFLICT, "销售订单状态不允许当前操作"),

	SALES_SHIPMENT_STATUS_INVALID(HttpStatus.CONFLICT, "销售出库状态不允许当前操作"),

	SALES_ORDER_EMPTY_LINES(HttpStatus.BAD_REQUEST, "销售订单明细不能为空"),

	SALES_SHIPMENT_EMPTY_LINES(HttpStatus.BAD_REQUEST, "销售出库明细不能为空"),

	SALES_CUSTOMER_INVALID(HttpStatus.BAD_REQUEST, "客户不存在或已停用"),

	SALES_WAREHOUSE_INVALID(HttpStatus.BAD_REQUEST, "销售出库仓库不存在或已停用"),

	SALES_RESERVATION_WAREHOUSE_REQUIRED(HttpStatus.BAD_REQUEST, "销售订单明细预留仓库必填"),

	SALES_MATERIAL_INVALID(HttpStatus.BAD_REQUEST, "销售物料不存在或已停用"),

	SALES_MATERIAL_NOT_SELLABLE(HttpStatus.BAD_REQUEST, "物料类型当前不可销售"),

	SALES_UNIT_INVALID(HttpStatus.BAD_REQUEST, "销售单位不存在、已停用或不是物料基本单位"),

	SALES_QUANTITY_INVALID(HttpStatus.BAD_REQUEST, "销售或出库数量不正确"),

	SALES_UNIT_PRICE_INVALID(HttpStatus.BAD_REQUEST, "销售单价不正确"),

	SALES_ORDER_DUPLICATE_LINE(HttpStatus.CONFLICT, "销售订单明细物料重复"),

	SALES_SHIPMENT_DUPLICATE_LINE(HttpStatus.CONFLICT, "销售出库明细来源订单行重复"),

	SALES_SHIPMENT_EXCEEDS_ORDER(HttpStatus.CONFLICT, "销售出库数量超过订单未出库数量"),

	SALES_SHIPMENT_LINE_SOURCE_INVALID(HttpStatus.CONFLICT, "销售出库明细来源不正确"),

	SALES_SHIPMENT_RESERVATION_WAREHOUSE_MISMATCH(HttpStatus.CONFLICT, "销售出库仓库必须与订单行预留仓库一致"),

	SALES_SHIPMENT_EARLY_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "提前交付原因必填"),

	SALES_STOCK_NOT_ENOUGH(HttpStatus.CONFLICT, "销售出库库存不足"),

	SALES_SHIPMENT_POSTED_IMMUTABLE(HttpStatus.CONFLICT, "已过账销售出库单不可编辑"),

	SALES_DUPLICATE_POST(HttpStatus.CONFLICT, "销售出库单已过账或重复过账"),

	SALES_MOVEMENT_SOURCE_DUPLICATED(HttpStatus.CONFLICT, "销售来源明细已生成库存变动"),

	SALES_QUOTE_NOT_FOUND(HttpStatus.NOT_FOUND, "销售报价不存在"),

	SALES_QUOTE_STATUS_INVALID(HttpStatus.CONFLICT, "销售报价状态不允许当前操作"),

	SALES_QUOTE_EMPTY_LINES(HttpStatus.BAD_REQUEST, "销售报价明细不能为空"),

	SALES_QUOTE_DUPLICATE_LINE(HttpStatus.CONFLICT, "销售报价明细行号重复"),

	SALES_CURRENCY_UNSUPPORTED(HttpStatus.BAD_REQUEST, "销售首版仅支持 CNY"),

	SALES_TAX_PRICE_INVALID(HttpStatus.BAD_REQUEST, "销售税价不合法"),

	SALES_ACTION_IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, "销售业务动作幂等键冲突"),

	SALES_CREDIT_BLOCKED(HttpStatus.CONFLICT, "客户信用检查未通过"),

	SALES_CREDIT_PROFILE_MISSING(HttpStatus.CONFLICT, "客户信用档案缺失"),

	SALES_CREDIT_LIMIT_EXCEEDED(HttpStatus.CONFLICT, "客户信用额度不足"),

	SALES_CREDIT_FROZEN(HttpStatus.CONFLICT, "客户信用已冻结"),

	SALES_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "销售对象版本已变化"),

	SALES_ORDER_SNAPSHOT_INVALID(HttpStatus.CONFLICT, "销售订单商业快照不完整"),

	SALES_ORDER_CHANGE_NOT_FOUND(HttpStatus.NOT_FOUND, "销售订单变更不存在"),

	SALES_ORDER_CHANGE_STATUS_INVALID(HttpStatus.CONFLICT, "销售订单变更状态不允许当前操作"),

	SALES_ORDER_CHANGE_BELOW_SHIPPED(HttpStatus.CONFLICT, "订单变更目标数量不能小于已出库数量"),

	SALES_ORDER_CHANGE_SOURCE_IMMUTABLE(HttpStatus.CONFLICT, "订单变更不得改变来源、物料或单位"),

	SALES_DELIVERY_PLAN_NOT_FOUND(HttpStatus.NOT_FOUND, "销售交付计划不存在"),

	SALES_DELIVERY_PLAN_TOTAL_MISMATCH(HttpStatus.CONFLICT, "销售交付计划总量与订单行不一致"),

	SALES_DELIVERY_PLAN_BELOW_SHIPPED(HttpStatus.CONFLICT, "销售交付计划数量不能小于已出库数量"),

	SALES_DELIVERY_PLAN_STATUS_INVALID(HttpStatus.CONFLICT, "销售交付计划状态不允许当前操作"),

	SALES_ORDER_CLOSE_BLOCKED(HttpStatus.CONFLICT, "销售订单关闭条件不满足"),

	SALES_ORDER_SHORT_CLOSE_APPROVAL_REQUIRED(HttpStatus.CONFLICT, "销售订单短交关闭必须先通过审批"),

	PROJECT_NOT_FOUND(HttpStatus.NOT_FOUND, "销售项目不存在"),

	PROJECT_STATUS_INVALID(HttpStatus.CONFLICT, "销售项目状态不允许当前操作"),

	PROJECT_MAIN_CONTRACT_REQUIRED(HttpStatus.CONFLICT, "项目激活需要已生效主合同"),

	PROJECT_HAS_EFFECTIVE_BUSINESS(HttpStatus.CONFLICT, "项目已有有效合同或销售订单，不能取消"),

	PROJECT_HAS_OPEN_BUSINESS(HttpStatus.CONFLICT, "项目仍有关联合同或销售订单未终态，不能关闭"),

	PROJECT_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "销售项目状态操作原因必填"),

	PROJECT_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "销售项目并发更新冲突"),

	CONTRACT_NOT_FOUND(HttpStatus.NOT_FOUND, "销售项目合同不存在"),

	CONTRACT_STATUS_INVALID(HttpStatus.CONFLICT, "销售项目合同状态不允许当前操作"),

	CONTRACT_PROJECT_NOT_ACTIVE(HttpStatus.CONFLICT, "补充合同要求项目已激活"),

	CONTRACT_MAIN_REQUIRED(HttpStatus.BAD_REQUEST, "补充合同必须引用主合同"),

	CONTRACT_MAIN_INVALID(HttpStatus.CONFLICT, "补充合同主合同不合法"),

	CONTRACT_MAIN_NOT_EFFECTIVE(HttpStatus.CONFLICT, "补充合同要求主合同已生效"),

	CONTRACT_AMOUNT_INVALID(HttpStatus.BAD_REQUEST, "合同金额不合法"),

	CONTRACT_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "销售项目合同状态操作原因必填"),

	CONTRACT_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "销售项目合同并发更新冲突"),

	CONTRACT_REFERENCED_BY_ORDER(HttpStatus.CONFLICT, "合同已被销售订单引用，不允许取消"),

	SALES_ORDER_PROJECT_PAIR_REQUIRED(HttpStatus.BAD_REQUEST, "销售订单项目与合同必须同时为空或同时有值"),

	SALES_ORDER_PROJECT_INVALID(HttpStatus.CONFLICT, "销售订单关联项目不合法"),

	SALES_ORDER_CONTRACT_INVALID(HttpStatus.CONFLICT, "销售订单关联合同不合法"),

	SALES_ORDER_PROJECT_CUSTOMER_MISMATCH(HttpStatus.CONFLICT, "销售订单客户与项目客户不一致"),

	SALES_ORDER_PROJECT_IMMUTABLE(HttpStatus.CONFLICT, "非草稿销售订单不可修改项目合同关联"),

	SALES_ORDER_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "销售订单并发更新冲突"),

	COST_RECORD_NOT_FOUND(HttpStatus.NOT_FOUND, "成本记录不存在"),

	COST_WORK_ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "成本关联工单不存在"),

	COST_WORK_ORDER_STATUS_INVALID(HttpStatus.CONFLICT, "工单状态不允许成本记录"),

	COST_SOURCE_DOCUMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "成本来源单据不存在"),

	COST_SOURCE_DOCUMENT_STATUS_INVALID(HttpStatus.CONFLICT, "成本来源单据状态无效"),

	COST_SOURCE_DUPLICATED(HttpStatus.CONFLICT, "成本来源已归集"),

	COST_TYPE_INVALID(HttpStatus.BAD_REQUEST, "成本类型不合法"),

	COST_BASIS_INVALID(HttpStatus.BAD_REQUEST, "成本口径不合法"),

	COST_QUANTITY_INVALID(HttpStatus.BAD_REQUEST, "成本数量不合法"),

	COST_AMOUNT_INVALID(HttpStatus.BAD_REQUEST, "成本金额不合法"),

	COST_GENERATED_RECORD_IMMUTABLE(HttpStatus.CONFLICT, "自动生成记录来源字段不可修改"),

	PROJECT_COST_PROJECT_INVALID(HttpStatus.BAD_REQUEST, "项目成本核算项目不合法"),

	PROJECT_COST_SOURCE_CHANGED(HttpStatus.CONFLICT, "项目成本来源已变化，请重新计算"),

	PROJECT_COST_SOURCE_UNVALUED(HttpStatus.CONFLICT, "项目成本来源未完成估值"),

	PROJECT_COST_SOURCE_CROSS_PROJECT(HttpStatus.CONFLICT, "项目成本来源项目归属不一致"),

	PROJECT_COST_SOURCE_BROKEN(HttpStatus.CONFLICT, "项目成本来源链路不完整"),

	PROJECT_COST_LABOR_UNPRICED(HttpStatus.CONFLICT, "项目成本存在未定价人工来源"),

	PROJECT_COST_DELIVERY_UNMATCHED(HttpStatus.CONFLICT, "项目成本发货与完工数量不匹配"),

	PROJECT_COST_ADJUSTMENT_OVER_ALLOCATED(HttpStatus.CONFLICT, "公共费用分配超过可用金额"),

	PROJECT_COST_VERSION_CONFLICT(HttpStatus.CONFLICT, "项目成本对象版本已变化"),

	PROJECT_COST_IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, "项目成本业务幂等键冲突"),

	PROJECT_COST_ACTION_NOT_ALLOWED(HttpStatus.CONFLICT, "当前项目成本状态不允许此操作"),

	PROJECT_COST_AMOUNT_FORBIDDEN(HttpStatus.FORBIDDEN, "无权查看项目成本金额"),

	FINANCE_RECEIVABLE_NOT_FOUND(HttpStatus.NOT_FOUND, "应收不存在"),

	FINANCE_RECEIPT_NOT_FOUND(HttpStatus.NOT_FOUND, "收款不存在"),

	FINANCE_PAYABLE_NOT_FOUND(HttpStatus.NOT_FOUND, "应付不存在"),

	FINANCE_PAYMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "付款不存在"),

	FINANCE_SOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "来源单据不存在"),

	FINANCE_SOURCE_STATUS_INVALID(HttpStatus.CONFLICT, "来源单据状态不允许生成往来"),

	FINANCE_SOURCE_DUPLICATED(HttpStatus.CONFLICT, "来源明细已生成往来"),

	FINANCE_AMOUNT_INVALID(HttpStatus.BAD_REQUEST, "金额不合法"),

	FINANCE_ALLOCATION_EXCEEDS_BALANCE(HttpStatus.CONFLICT, "收付款金额超过未结余额"),

	FINANCE_STATUS_NOT_ALLOWED(HttpStatus.CONFLICT, "当前状态不允许操作"),

	FINANCE_POSTED_IMMUTABLE(HttpStatus.CONFLICT, "已过账收付款不可编辑或取消"),

	FINANCE_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "并发更新冲突"),

	FINANCE_DUE_DATE_INVALID(HttpStatus.BAD_REQUEST, "到期日期不合法"),

	FINANCE_METHOD_INVALID(HttpStatus.BAD_REQUEST, "收付款方式不合法"),

	FINANCE_INVOICE_NOT_FOUND(HttpStatus.NOT_FOUND, "发票不存在"),

	FINANCE_EXPENSE_NOT_FOUND(HttpStatus.NOT_FOUND, "费用单不存在"),

	FINANCE_SETTLEMENT_ALLOCATION_NOT_FOUND(HttpStatus.NOT_FOUND, "核销单不存在"),

	FINANCE_VOUCHER_DRAFT_NOT_FOUND(HttpStatus.NOT_FOUND, "凭证草稿不存在"),

	FINANCE_MATCH_EXCEPTION(HttpStatus.CONFLICT, "采购发票匹配存在差异"),

	FINANCE_SOURCE_MISMATCH(HttpStatus.CONFLICT, "来源与当前财务对象不匹配"),

	FINANCE_SOURCE_OVER_INVOICED(HttpStatus.CONFLICT, "来源已生成有效发票"),

	FINANCE_SETTLEMENT_BALANCE_INSUFFICIENT(HttpStatus.CONFLICT, "可核销余额不足"),

	FINANCE_CROSS_PARTY_OR_PROJECT(HttpStatus.CONFLICT, "往来对象或项目归属不一致"),

	FINANCE_IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, "财务业务幂等键冲突"),

	FINANCE_SENSITIVE_FORBIDDEN(HttpStatus.FORBIDDEN, "缺少结算敏感资料权限"),

	REPORT_DATE_RANGE_INVALID(HttpStatus.BAD_REQUEST, "报表日期范围非法"),

	REPORT_PARAMETER_INVALID(HttpStatus.BAD_REQUEST, "报表查询参数非法"),

	REPORT_TRACE_KEY_INVALID(HttpStatus.BAD_REQUEST, "报表追溯键非法"),

	REPORT_BASIS_INVALID(HttpStatus.BAD_REQUEST, "报表口径非法"),

	REPORT_PERIOD_UNAVAILABLE(HttpStatus.BAD_REQUEST, "报表期间不可用"),

	REPORT_SNAPSHOT_NOT_INCLUDED(HttpStatus.BAD_REQUEST, "报表快照未包含"),

	REPORT_SOURCE_INCOMPLETE(HttpStatus.CONFLICT, "报表来源不完整"),

	REVERSAL_SOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "反向业务来源不存在"),

	REVERSAL_SOURCE_STATUS_INVALID(HttpStatus.CONFLICT, "来源状态不允许反向业务"),

	REVERSAL_STATUS_NOT_ALLOWED(HttpStatus.CONFLICT, "当前反向单据状态不允许操作"),

	REVERSAL_QUANTITY_INVALID(HttpStatus.BAD_REQUEST, "反向业务数量不合法"),

	REVERSAL_AMOUNT_INVALID(HttpStatus.BAD_REQUEST, "反向业务金额不合法"),

	REVERSAL_QUANTITY_EXCEEDS_AVAILABLE(HttpStatus.CONFLICT, "反向业务数量超过可用数量"),

	REVERSAL_AMOUNT_EXCEEDS_AVAILABLE(HttpStatus.CONFLICT, "反向业务金额超过可冲金额"),

	REVERSAL_STOCK_INSUFFICIENT(HttpStatus.CONFLICT, "反向出库库存不足"),

	REVERSAL_DUPLICATED(HttpStatus.CONFLICT, "反向业务重复"),

	REVERSAL_POSTED_IMMUTABLE(HttpStatus.CONFLICT, "已过账反向单不可编辑"),

	REVERSAL_TRACE_RESTRICTED(HttpStatus.FORBIDDEN, "反向业务来源追溯受限"),

	REVERSAL_CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "反向业务并发更新冲突"),

	BUSINESS_PERIOD_LOCKED(HttpStatus.CONFLICT, "业务期间已锁定"),

	BUSINESS_PERIOD_OVERLAPPED(HttpStatus.CONFLICT, "业务期间日期范围重叠"),

	BUSINESS_PERIOD_DATE_RANGE_INVALID(HttpStatus.BAD_REQUEST, "业务期间日期范围不合法"),

	BUSINESS_PERIOD_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "业务期间操作原因必填"),

	BUSINESS_PERIOD_NOT_FOUND(HttpStatus.NOT_FOUND, "业务期间不存在"),

	BUSINESS_PERIOD_STATUS_INVALID(HttpStatus.CONFLICT, "业务期间状态不允许当前操作"),

	PERIOD_CLOSE_NOT_FOUND(HttpStatus.NOT_FOUND, "业务月结运行不存在"),

	PERIOD_CLOSE_PERIOD_INVALID(HttpStatus.BAD_REQUEST, "业务月结期间不合法"),

	PERIOD_CLOSE_ALREADY_CLOSED(HttpStatus.CONFLICT, "业务期间已存在当前月结版本"),

	PERIOD_CLOSE_CHECK_REQUIRED(HttpStatus.CONFLICT, "业务月结关闭前必须先完成检查"),

	PERIOD_CLOSE_BLOCKED(HttpStatus.CONFLICT, "业务月结存在阻断项，不能关闭"),

	PERIOD_CLOSE_WARNING_ACK_REQUIRED(HttpStatus.CONFLICT, "业务月结警告需要确认并填写原因"),

	PERIOD_CLOSE_SOURCE_CHANGED(HttpStatus.CONFLICT, "业务月结来源已变化，请重新检查"),

	PERIOD_CLOSE_VERSION_CONFLICT(HttpStatus.CONFLICT, "业务月结版本已变化，请刷新后重试"),

	PERIOD_CLOSE_IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, "业务月结幂等键冲突"),

	PERIOD_CLOSE_ACTION_NOT_ALLOWED(HttpStatus.CONFLICT, "当前业务月结状态不允许此操作"),

	PERIOD_CLOSE_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "业务月结操作原因必填"),

	PERIOD_CLOSE_SNAPSHOT_INCOMPLETE(HttpStatus.CONFLICT, "业务月结快照不完整"),

	FIN_CLOSE_NOT_READY(HttpStatus.CONFLICT, "财务结账检查未就绪，不能关闭"),

	FIN_CLOSE_STALE(HttpStatus.CONFLICT, "财务结账来源已变化，请重新检查"),

	FIN_CLOSE_PERIOD_CLOSED(HttpStatus.CONFLICT, "会计期间已财务结账关闭，不允许写入"),

	FIN_CLOSE_CONFLICT(HttpStatus.CONFLICT, "财务结账对象冲突，请刷新后重试"),

	FIN_REOPEN_APPROVAL_REQUIRED(HttpStatus.CONFLICT, "财务反结账必须先通过审批"),

	FIN_PROFIT_LOSS_STALE(HttpStatus.CONFLICT, "损益结转来源已变化，请重新预览"),

	FIN_BANK_MATCH_AMOUNT_INVALID(HttpStatus.BAD_REQUEST, "银行对账匹配金额不合法"),

	FIN_BANK_RECON_NOT_BALANCED(HttpStatus.CONFLICT, "银行对账未平衡，不能确认"),

	FIN_TAX_SUMMARY_STALE(HttpStatus.CONFLICT, "税务汇总来源已变化，请重新计算"),

	FIN_TAX_SOURCE_CHANGED(HttpStatus.CONFLICT, "税务来源已变化，请重新计算"),

	FIN_PERMISSION_DENIED(HttpStatus.FORBIDDEN, "缺少财务结账权限"),

	GL_LEDGER_ALREADY_INITIALIZED(HttpStatus.CONFLICT, "总账已启用，不能更换启用期间"),

	GL_LEDGER_NOT_INITIALIZED(HttpStatus.CONFLICT, "总账尚未启用"),

	GL_ACCOUNT_NOT_FOUND(HttpStatus.NOT_FOUND, "会计科目不存在"),

	GL_ACCOUNT_NOT_LEAF(HttpStatus.BAD_REQUEST, "只能使用末级会计科目"),

	GL_ACCOUNT_DISABLED(HttpStatus.CONFLICT, "会计科目已停用"),

	GL_ACCOUNT_LOCKED(HttpStatus.CONFLICT, "会计科目已有总账事实，不允许当前修改"),

	GL_AUXILIARY_REQUIRED(HttpStatus.BAD_REQUEST, "缺少必填辅助核算"),

	GL_AUXILIARY_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "当前科目不允许该辅助核算"),

	GL_PERIOD_NOT_FOUND(HttpStatus.NOT_FOUND, "会计期间不存在"),

	GL_PERIOD_NOT_OPEN(HttpStatus.CONFLICT, "会计期间未开放"),

	GL_RULE_MISSING(HttpStatus.CONFLICT, "缺少有效制证规则"),

	GL_RULE_AMBIGUOUS(HttpStatus.CONFLICT, "有效制证规则不唯一"),

	GL_RULE_INVALID(HttpStatus.BAD_REQUEST, "制证规则不合法"),

	GL_VOUCHER_NOT_FOUND(HttpStatus.NOT_FOUND, "正式凭证不存在"),

	GL_VOUCHER_UNBALANCED(HttpStatus.BAD_REQUEST, "凭证借贷不平衡"),

	GL_SOURCE_NOT_READY(HttpStatus.CONFLICT, "来源单据未就绪或状态已变化"),

	GL_SOURCE_ALREADY_ACCOUNTED(HttpStatus.CONFLICT, "来源单据已被正式凭证占用"),

	GL_SOURCE_CHANGED(HttpStatus.CONFLICT, "来源会计事实已变化，请刷新后重试"),

	GL_POSTED_IMMUTABLE(HttpStatus.CONFLICT, "已记账凭证不可修改"),

	GL_APPROVAL_SELF_FORBIDDEN(HttpStatus.FORBIDDEN, "提交人不能审批并记账自己的凭证"),

	GL_VOUCHER_NUMBER_CONFLICT(HttpStatus.CONFLICT, "凭证连续编号冲突"),

	GL_VERSION_CONFLICT(HttpStatus.CONFLICT, "总账对象版本已变化，请刷新后重试"),

	GL_IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, "总账业务幂等键冲突"),

	GL_REVERSAL_ALREADY_EXISTS(HttpStatus.CONFLICT, "原凭证已存在有效冲销凭证"),

	GL_TRIAL_BALANCE_MISMATCH(HttpStatus.CONFLICT, "试算平衡与总账汇总缓存不一致"),

	CONFLICT("CONFLICT", "数据冲突", HttpStatus.CONFLICT),

	SYSTEM_ERROR("SYSTEM_ERROR", "系统异常", HttpStatus.INTERNAL_SERVER_ERROR);

	private final String code;

	private final String message;

	private final HttpStatus httpStatus;

	ApiErrorCode(String code, String message, HttpStatus httpStatus) {
		this.code = code;
		this.message = message;
		this.httpStatus = httpStatus;
	}

	ApiErrorCode(HttpStatus httpStatus, String message) {
		this.code = name();
		this.message = message;
		this.httpStatus = httpStatus;
	}

	public String code() {
		return this.code;
	}

	public String message() {
		return this.message;
	}

	public HttpStatus httpStatus() {
		return this.httpStatus;
	}

}
